// Plain-text / markdown rendering of a QA report, decoupled from any specific
// standards catalog. Standard labels come from each objective's `standardLabel`
// (set by the caller), so this works for both the demo and real Compass data.

import {
  RULE_CATEGORY_LABELS,
  type EngineCourse,
  type QaReport,
  type Severity,
} from "./engine.ts";

function severitySymbol(severity: Severity): string {
  if (severity === "pass") return "[pass]";
  if (severity === "warn") return "[warn]";
  return "[fail]";
}

export interface RenderOptions {
  /** Footer line; defaults to a neutral attribution. */
  generatedBy?: string;
}

/** Render a markdown handoff / evidence report for export. */
export function renderQaReportMarkdown(
  course: EngineCourse,
  report: QaReport,
  options: RenderOptions = {},
): string {
  const lines: string[] = [];
  lines.push(`# ${course.title || "Untitled course"} - Curriculum QA Report`);
  lines.push("");
  if (course.gradeBand !== undefined) {
    lines.push(`Audience: ${course.gradeBand || "Not set"}`);
  }
  lines.push(
    `Term length: ${course.termWeeks ? `${course.termWeeks} weeks` : "Not set"}`,
  );
  lines.push(`Overall QA score: ${report.score}%`);
  lines.push(
    `Checks: ${report.counts.pass} passed, ${report.counts.warn} advisory, ${report.counts.fail} to fix`,
  );
  lines.push("");

  lines.push("## Category scores");
  for (const c of report.categoryScores) {
    lines.push(`- ${RULE_CATEGORY_LABELS[c.category]}: ${c.score}%`);
  }
  lines.push("");

  lines.push("## Learning outcomes");
  course.objectives.forEach((o, i) => {
    const analysis = report.objectiveAnalyses.find((a) => a.objectiveId === o.id);
    lines.push(`${i + 1}. ${o.text || "Untitled outcome"}`);
    lines.push(
      `   Bloom level: ${analysis?.detection.bloomLevel ?? "not detected"}; Standard: ${o.standardLabel ?? (o.standardId ? "mapped" : "unmapped")}; Assessments: ${analysis?.assessmentCount ?? 0}`,
    );
  });
  lines.push("");

  lines.push("## Assessments");
  course.assessments.forEach((a, i) => {
    lines.push(
      `${i + 1}. ${a.title || "Untitled assessment"}${a.type ? ` (${a.type})` : ""}`,
    );
  });
  lines.push("");

  const openItems = report.findings.filter((f) => f.severity !== "pass");
  lines.push("## Items to resolve");
  if (openItems.length === 0) {
    lines.push("None. All checks passed.");
  } else {
    for (const f of openItems) {
      lines.push(`- ${severitySymbol(f.severity)} ${f.targetLabel}: ${f.message}`);
      if (f.remediation) lines.push(`  Fix: ${f.remediation}`);
    }
  }
  lines.push("");
  lines.push(options.generatedBy ?? "Generated by the Synops Curriculum engine.");
  return lines.join("\n");
}
