import { Router } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import platformRouter from "./platform";
import usersRouter from "./users";
import partnersRouter from "./partners";
import organisationsRouter from "./organisations";
import brandRouter from "./brand";
import coursesRouter from "./courses";
import modulesRouter from "./modules";
import beatsRouter from "./beats";
import studioRouter from "./studio";
import sessionsRouter from "./sessions";
import assessmentsRouter from "./assessments";
import credentialsRouter from "./credentials";
import coachRouter from "./coach";
import analyticsRouter from "./analytics";
import reportsRouter from "./reports";
import enrolmentsRouter from "./enrolments";
import discussionsRouter from "./discussions";
import announcementsRouter from "./announcements";
import assignmentsRouter from "./assignments";
import gradebookRouter from "./gradebook";
import calendarRouter from "./calendar";
import pagesRouter from "./pages";
import groupsRouter from "./groups";
import notificationsRouter from "./notifications";
import interactiveVideoRouter from "./interactive_video";
import learnRouter from "./learn";
import coachAreaRouter from "./coachArea";
import progressRouter from "./progress";
import activitiesRouter from "./activities";
import moduleReadingsRouter from "./moduleReadings";
import activityEmbedRouter from "./activityEmbed";
import supportRouter from "./support";
import whatsappRouter from "./whatsapp";
import funderRouter from "./funder";
import deliveryRouter from "./delivery";
import complianceRouter from "./compliance";
import accreditationRouter from "./accreditation";
import accessRequestsRouter from "./accessRequests";
import promptTemplatesRouter from "./promptTemplates";
import casesRouter from "./cases";
import caseEmbedRouter from "./caseEmbed";
import tutorFiguresRouter from "./tutorFigures";
import learningHubRouter from "./learningHub";
import billingRouter from "./billing";
import documentsRouter from "./documents";
import partnerCommsRouter from "./partnerComms";
import devRouter, { devRoutesEnabled } from "./dev";

const router = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(platformRouter);
router.use(usersRouter);
router.use(partnersRouter);
router.use(organisationsRouter);
router.use(brandRouter);
router.use(coursesRouter);
router.use(modulesRouter);
router.use(beatsRouter);
router.use(studioRouter);
router.use(sessionsRouter);
router.use(assessmentsRouter);
router.use(credentialsRouter);
router.use(coachRouter);
router.use(analyticsRouter);
router.use(reportsRouter);
router.use(enrolmentsRouter);
router.use(discussionsRouter);
router.use(announcementsRouter);
router.use(assignmentsRouter);
router.use(gradebookRouter);
router.use(calendarRouter);
router.use(pagesRouter);
router.use(groupsRouter);
router.use(notificationsRouter);
router.use(interactiveVideoRouter);
router.use(learnRouter);
router.use(coachAreaRouter);
router.use(progressRouter);
router.use(activitiesRouter);
router.use(moduleReadingsRouter);
router.use(activityEmbedRouter);
router.use(supportRouter);
router.use(whatsappRouter);
router.use(funderRouter);
router.use(deliveryRouter);
router.use(complianceRouter);
router.use(accreditationRouter);
router.use(accessRequestsRouter);
router.use(promptTemplatesRouter);
router.use(casesRouter);
router.use(caseEmbedRouter);
router.use(tutorFiguresRouter);
router.use(learningHubRouter);
router.use(billingRouter);
router.use(documentsRouter);
router.use(partnerCommsRouter);
// Defense in depth: the dev router is not even mounted unless explicitly enabled (see routes/dev.ts).
if (devRoutesEnabled) router.use(devRouter);

export default router;
