import { pgTable, text, timestamp, numeric, boolean, jsonb, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Interactive HTML activities.
 *
 * An activity is author-supplied HTML (with optional CSS/JS) that a learner completes
 * in a SANDBOXED iframe. The activity reports a result back via postMessage; the parent
 * page -- the only thing holding the session cookie -- persists it as a submission that
 * a coach can review. Modelled on interactive_video (definition table + response table),
 * plus the submissions review flow.
 *
 * SECURITY NOTE for anyone extending this: the HTML is untrusted author content. It is
 * rendered with sandbox="allow-scripts" and WITHOUT allow-same-origin, so it runs in an
 * opaque origin and can never read the parent's cookies or DOM. Do not add
 * allow-same-origin to that iframe.
 */

export const activitySubmissionStatusEnum = pgEnum("activity_submission_status", [
  "submitted",
  "reviewed",
  "approved",
]);

export const interactiveActivitiesTable = pgTable("interactive_activities", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  // Generic tenant id (organisation OR partner), mirroring cases. null = platform library.
  organisationId: text("organisation_id"),
  // Optional links so an activity can live inside a module/course or stand alone.
  courseId: text("course_id"),
  moduleId: text("module_id"),
  title: text("title").notNull(),
  instructions: text("instructions"),
  // The author-supplied HTML document body. Rendered inside a sandboxed iframe.
  html: text("html").notNull().default(""),
  /**
   * How the activity was authored / how it renders:
   *  - "html":  self-contained author HTML in the sandbox player (default, original behaviour).
   *  - "embed": an external embed (embedUrl set -> iframe to that URL; else html is a paste-in
   *             snippet like a YouTube/Genially/Google Form iframe).
   *  - "ai":    generated by the AI activity generator (also self-contained HTML).
   */
  source: text("source", { enum: ["html", "embed", "ai"] }).notNull().default("html"),
  /** For source="embed": the external URL to iframe (e.g. a Genially / Google Form share URL). */
  embedUrl: text("embed_url"),
  /** Activity kind (quiz, flashcards, drag_drop, matching, scenario, hotspot, embed, custom). */
  kind: text("kind").notNull().default("custom"),
  /** Rigor: Bloom's cognitive level (Remember..Create) + difficulty band. AI-determined, overridable. */
  bloomsLevel: text("blooms_level"),
  difficulty: text("difficulty", { enum: ["foundational", "intermediate", "advanced"] }),
  /** Hub authors can publish an activity to the shared platform library (organisationId null). */
  isLibrary: boolean("is_library").notNull().default(false),
  tags: text("tags").array(),
  // Points the activity is worth; the reported result may include a raw score.
  maxScore: numeric("max_score", { precision: 7, scale: 2 }).notNull().default("100"),
  published: boolean("published").notNull().default(false),
  createdByUserId: text("created_by_user_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertInteractiveActivitySchema = createInsertSchema(interactiveActivitiesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertInteractiveActivity = z.infer<typeof insertInteractiveActivitySchema>;
export type InteractiveActivity = typeof interactiveActivitiesTable.$inferSelect;

export const activitySubmissionsTable = pgTable("activity_submissions", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  activityId: text("activity_id").notNull(),
  userId: text("user_id").notNull(),
  // Whatever the activity chose to report: answers, state, a self-reported score, etc.
  payload: jsonb("payload").notNull().default({}),
  // Optional numeric score the activity reported (0..maxScore). Coach can override.
  score: numeric("score", { precision: 7, scale: 2 }),
  status: activitySubmissionStatusEnum("status").notNull().default("submitted"),
  feedback: text("feedback"),
  reviewedBy: text("reviewed_by"),
  submittedAt: timestamp("submitted_at").notNull().defaultNow(),
  reviewedAt: timestamp("reviewed_at"),
});

export const insertActivitySubmissionSchema = createInsertSchema(activitySubmissionsTable).omit({
  id: true,
  status: true,
  feedback: true,
  reviewedBy: true,
  submittedAt: true,
  reviewedAt: true,
});
export type InsertActivitySubmission = z.infer<typeof insertActivitySubmissionSchema>;
export type ActivitySubmission = typeof activitySubmissionsTable.$inferSelect;

/**
 * Signed public embed link for an activity (mirrors case_embed_links). An opaque token runs
 * the activity WITHOUT authentication, so it can be pasted into an LMS/site like Google Sites.
 */
export const activityEmbedLinksTable = pgTable("activity_embed_links", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  activityId: text("activity_id").notNull(),
  organisationId: text("organisation_id"),
  createdBy: text("created_by").notNull(),
  token: text("token").notNull().unique(),
  label: text("label"),
  expiresAt: timestamp("expires_at"),
  isActive: boolean("is_active").notNull().default(true),
  accessCount: numeric("access_count", { precision: 12, scale: 0 }).notNull().default("0"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export type ActivityEmbedLink = typeof activityEmbedLinksTable.$inferSelect;

/**
 * Activity distribution chain: Partner -> Organisation -> Learner (mirrors case_assignments).
 * Explicit at each tier; status rolls up from activity_submissions.
 */
export const activityAssignmentsTable = pgTable("activity_assignments", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  activityId: text("activity_id").notNull(),
  tier: text("tier", { enum: ["partner", "organisation", "learner"] }).notNull(),
  partnerId: text("partner_id"),
  organisationId: text("organisation_id"),
  userId: text("user_id"),
  groupId: text("group_id"),
  parentAssignmentId: text("parent_assignment_id"),
  assignedBy: text("assigned_by").notNull(),
  assignedByName: text("assigned_by_name"),
  status: text("status", { enum: ["assigned", "in_progress", "completed", "revoked"] }).notNull().default("assigned"),
  dueDate: timestamp("due_date"),
  assignedAt: timestamp("assigned_at").notNull().defaultNow(),
  completedAt: timestamp("completed_at"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
export type ActivityAssignment = typeof activityAssignmentsTable.$inferSelect;
