export interface RegionInfo {
  id: string;
  label: string;
  description: string;
  curriculumLabel: string;
  conventionsHint: string;
  subjects: string[];
  yearGroups: { value: string; label: string }[];
}

const yg = (value: string, label: string) => ({ value, label });

export const REGIONS: RegionInfo[] = [
  {
    id: "us",
    label: "United States",
    description: "Common Core / state standards.",
    curriculumLabel: "Common Core and US state standards",
    conventionsHint:
      "Use US spelling and grade-level vocabulary (e.g. Grade 7), and reference Common Core or relevant state standards where applicable. US-style examples are welcome, but rotate student names, settings, and cultural references across the full diversity of US life (African American, Latino, Asian American, Native American, immigrant, urban and rural), and include international perspectives so students see themselves and the wider world.",
    subjects: [
      "Mathematics",
      "English Language Arts",
      "Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Earth and Space Science",
      "Social Studies",
      "US History",
      "World History",
      "Civics and Government",
      "Geography",
      "Economics",
      "Computer Science",
      "Health",
      "Physical Education",
      "Visual Arts",
      "Music",
      "Theater",
      "Spanish",
      "French",
      "Mandarin",
    ],
    yearGroups: [
      yg("K", "Kindergarten"),
      yg("1", "Grade 1"),
      yg("2", "Grade 2"),
      yg("3", "Grade 3"),
      yg("4", "Grade 4"),
      yg("5", "Grade 5"),
      yg("6", "Grade 6"),
      yg("7", "Grade 7"),
      yg("8", "Grade 8"),
      yg("9", "Grade 9"),
      yg("10", "Grade 10"),
      yg("11", "Grade 11"),
      yg("12", "Grade 12"),
      yg("UG1", "Undergraduate Year 1"),
      yg("UG2", "Undergraduate Year 2"),
      yg("UG3", "Undergraduate Year 3"),
      yg("UG4", "Undergraduate Year 4"),
      yg("PG", "Postgraduate"),
      yg("ADULT", "Adult Learner"),
      yg("VOC", "Vocational / CTE"),
    ],
  },
  {
    id: "uk",
    label: "United Kingdom",
    description: "National Curriculum / GCSE / A-Level.",
    curriculumLabel: "UK National Curriculum, GCSE, and A-Level",
    conventionsHint:
      "Use UK spelling and 'maths' not 'math', and reference Key Stages, GCSE, or A-Level specifications where appropriate. Reflect the full diversity of UK classrooms in names and contexts (including Black British, South Asian, East Asian, Eastern European, and Traveller heritages), and include non-UK examples so the resource does not present Britain as the centre of the world.",
    subjects: [
      "Mathematics",
      "English Language",
      "English Literature",
      "Combined Science",
      "Biology",
      "Chemistry",
      "Physics",
      "History",
      "Geography",
      "Religious Education",
      "Modern Foreign Languages",
      "French",
      "Spanish",
      "German",
      "Computing",
      "Design and Technology",
      "Art and Design",
      "Music",
      "Drama",
      "Physical Education",
      "PSHE",
      "Citizenship",
      "Business Studies",
    ],
    yearGroups: [
      yg("Reception", "Reception"),
      yg("Y1", "Year 1"),
      yg("Y2", "Year 2"),
      yg("Y3", "Year 3"),
      yg("Y4", "Year 4"),
      yg("Y5", "Year 5"),
      yg("Y6", "Year 6"),
      yg("Y7", "Year 7"),
      yg("Y8", "Year 8"),
      yg("Y9", "Year 9"),
      yg("Y10", "Year 10"),
      yg("Y11", "Year 11"),
      yg("Y12", "Year 12"),
      yg("Y13", "Year 13"),
      yg("UG1", "Undergraduate Year 1"),
      yg("UG2", "Undergraduate Year 2"),
      yg("UG3", "Undergraduate Year 3"),
      yg("UG4", "Undergraduate Year 4"),
      yg("PG", "Postgraduate"),
      yg("ADULT", "Adult Learner"),
      yg("VOC", "Further Education / Vocational"),
    ],
  },
  {
    id: "europe",
    label: "Europe",
    description: "IB and national European curricula.",
    curriculumLabel:
      "International Baccalaureate and national European curricula",
    conventionsHint:
      "Use British/international English. Default to IB conceptual framing where appropriate and cite typical European curriculum stages where relevant. Reflect the full diversity of European classrooms and treat European history as part of a global story, not its centre. Include examples and contributors from Africa, Asia, the Americas, and the Pacific as a matter of course.",
    subjects: [
      "Mathematics",
      "Language A (Literature)",
      "Language A (Language and Literature)",
      "Language B",
      "Biology",
      "Chemistry",
      "Physics",
      "Environmental Systems and Societies",
      "History",
      "Geography",
      "Economics",
      "Philosophy",
      "Psychology",
      "Computer Science",
      "Design Technology",
      "Visual Arts",
      "Music",
      "Theatre",
      "Physical Education",
      "Theory of Knowledge",
    ],
    yearGroups: [
      yg("PYP1", "PYP 1"),
      yg("PYP2", "PYP 2"),
      yg("PYP3", "PYP 3"),
      yg("PYP4", "PYP 4"),
      yg("PYP5", "PYP 5"),
      yg("MYP1", "MYP 1"),
      yg("MYP2", "MYP 2"),
      yg("MYP3", "MYP 3"),
      yg("MYP4", "MYP 4"),
      yg("MYP5", "MYP 5"),
      yg("DP1", "DP Year 1"),
      yg("DP2", "DP Year 2"),
      yg("UG1", "Undergraduate Year 1"),
      yg("UG2", "Undergraduate Year 2"),
      yg("UG3", "Undergraduate Year 3"),
      yg("UG4", "Undergraduate Year 4"),
      yg("PG", "Postgraduate"),
      yg("ADULT", "Adult Learner"),
      yg("VOC", "Vocational / VET"),
    ],
  },
  {
    id: "africa",
    label: "Africa",
    description: "National curricula across the continent.",
    curriculumLabel:
      "National curricula across African states (e.g. CBC in Kenya, NERDC in Nigeria, CAPS in South Africa)",
    conventionsHint:
      "Use clear international English. Default to African contexts, names, places, currencies (KES, NGN, ZAR, GHS, TZS, UGX, XOF), foods, and everyday scenarios across the continent (Kenya, Nigeria, South Africa, Ghana, Tanzania, Uganda, Senegal, Ethiopia, Egypt, Morocco, Zimbabwe, Rwanda, and others), not only one country. Reference local curriculum frameworks (CBC, CAPS, NERDC, WAEC, KCSE, ECZ) where the teacher indicates. Treat African contributions to mathematics, science, history, philosophy, literature, and the arts (e.g. Ishango bone, Yoruba numeration, Great Zimbabwe, Lalibela, Timbuktu manuscripts, Wangari Maathai, Chinua Achebe, Mariama Bâ, Ngũgĩ wa Thiong'o, Cheikh Anta Diop, Wole Soyinka) as central rather than exceptional. Do not romanticise colonialism, and where colonial history is relevant, name the peoples and resistance movements involved.",
    subjects: [
      "Mathematics",
      "English",
      "Integrated Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Agricultural Science",
      "Social Studies",
      "History",
      "Geography",
      "Religious Studies",
      "Civic Education",
      "Life Skills",
      "Kiswahili",
      "French",
      "Portuguese",
      "Arabic",
      "Information and Communication Technology",
      "Business Studies",
      "Home Economics",
      "Creative Arts",
      "Physical Education",
    ],
    yearGroups: [
      yg("PP1", "Pre-Primary 1"),
      yg("PP2", "Pre-Primary 2"),
      yg("P1", "Primary 1"),
      yg("P2", "Primary 2"),
      yg("P3", "Primary 3"),
      yg("P4", "Primary 4"),
      yg("P5", "Primary 5"),
      yg("P6", "Primary 6"),
      yg("JSS1", "Junior Secondary 1"),
      yg("JSS2", "Junior Secondary 2"),
      yg("JSS3", "Junior Secondary 3"),
      yg("SSS1", "Senior Secondary 1"),
      yg("SSS2", "Senior Secondary 2"),
      yg("SSS3", "Senior Secondary 3"),
      yg("UG1", "Undergraduate Year 1"),
      yg("UG2", "Undergraduate Year 2"),
      yg("UG3", "Undergraduate Year 3"),
      yg("UG4", "Undergraduate Year 4"),
      yg("PG", "Postgraduate"),
      yg("ADULT", "Adult Learner"),
      yg("VOC", "TVET"),
    ],
  },
  {
    id: "asia",
    label: "Asia",
    description: "National curricula across Asia.",
    curriculumLabel:
      "National curricula across Asia (e.g. CBSE/ICSE in India, MOE Singapore, MEXT Japan, KSSM Malaysia)",
    conventionsHint:
      "Use clear international English. Default to Asian contexts, names, places, currencies (INR, CNY, JPY, KRW, SGD, MYR, IDR, PHP, THB, VND, PKR, BDT), foods, festivals, and everyday scenarios across the region (India, China, Japan, Korea, Singapore, Malaysia, Indonesia, Philippines, Thailand, Vietnam, Pakistan, Bangladesh, Sri Lanka, Nepal, Mongolia, Central Asia, and others), not only one country. Reference the local curriculum framework where the teacher indicates. Treat Asian contributions to mathematics, science, philosophy, literature, and the arts (e.g. Indian origins of zero and algebra, Chinese astronomy and printing, Islamic Golden Age science, Korean han'gŭl, Japanese mathematicians like Seki Takakazu, writers like Rabindranath Tagore, Mo Yan, Arundhati Roy, Han Kang) as central rather than exceptional. Be respectful and accurate around religion, caste, and ethnicity.",
    subjects: [
      "Mathematics",
      "English",
      "Mother Tongue",
      "Science",
      "Biology",
      "Chemistry",
      "Physics",
      "Social Studies",
      "History",
      "Geography",
      "Economics",
      "Civics",
      "Moral Education",
      "Religious Studies",
      "Hindi",
      "Mandarin",
      "Malay",
      "Tamil",
      "Japanese",
      "Korean",
      "Information Technology",
      "Computer Studies",
      "Art",
      "Music",
      "Physical Education",
    ],
    yearGroups: [
      yg("P1", "Primary 1"),
      yg("P2", "Primary 2"),
      yg("P3", "Primary 3"),
      yg("P4", "Primary 4"),
      yg("P5", "Primary 5"),
      yg("P6", "Primary 6"),
      yg("S1", "Secondary 1"),
      yg("S2", "Secondary 2"),
      yg("S3", "Secondary 3"),
      yg("S4", "Secondary 4"),
      yg("S5", "Secondary 5"),
      yg("JC1", "Junior College 1"),
      yg("JC2", "Junior College 2"),
      yg("UG1", "Undergraduate Year 1"),
      yg("UG2", "Undergraduate Year 2"),
      yg("UG3", "Undergraduate Year 3"),
      yg("UG4", "Undergraduate Year 4"),
      yg("PG", "Postgraduate"),
      yg("ADULT", "Adult Learner"),
      yg("VOC", "TVET / Vocational"),
    ],
  },
];

export function getRegion(id: string): RegionInfo | undefined {
  return REGIONS.find((r) => r.id === id);
}

export const REGION_IDS = REGIONS.map((r) => r.id);
