// Samples library seed: a grade-appropriate worksheet + quiz for every school
// grade in each region (US, UK, Europe, Africa, Asia). Undergraduate / postgraduate
// / adult / vocational levels are intentionally excluded — this covers the school
// grade ladder so the Samples library has coverage for every grade level.
//
// Content matches the WorksheetContent / QuizContent shapes the app renders.

import { db, samplesTable } from "@workspace/paideia-db";
import { sql } from "drizzle-orm";
import { getRegion } from "./catalog.js";

type WType = "short" | "multiple_choice" | "long" | "calculation";
type QType = "multiple_choice" | "short_answer" | "true_false";
type Diff = "easy" | "medium" | "hard";

// Worksheet question tuple: [type, prompt, options|null, answer, workingOrRubric]
type WQ = [WType, string, string[] | null, string, string];
// Quiz item tuple: [type, prompt, options|null, correctAnswer, difficulty, skillAssessed]
type QI = [QType, string, string[] | null, string, Diff, string];

interface Spec {
  region: string;
  yg: string;
  subject: string;
  topic: string;
  wsInstr: string;
  wsNotes: string;
  ws: WQ[];
  qzFormat: string;
  qzInstr: string;
  qz: QI[];
}

const S = (
  region: string,
  yg: string,
  subject: string,
  topic: string,
  wsInstr: string,
  ws: WQ[],
  wsNotes: string,
  qzFormat: string,
  qzInstr: string,
  qz: QI[],
): Spec => ({ region, yg, subject, topic, wsInstr, wsNotes, ws, qzFormat, qzInstr, qz });

// ── United States (Kindergarten–Grade 12) ───────────────────────────────────
const US: Spec[] = [
  S("us", "K", "Mathematics", "Counting and Comparing Numbers to 10",
    "Count the objects and write the number. Then circle the group that has more.",
    [
      ["short", "How many stars? ★ ★ ★", null, "3", "Point and count one at a time: 1, 2, 3."],
      ["short", "How many circles? ● ● ● ● ●", null, "5", "Touch each circle as you count."],
      ["multiple_choice", "Which is more?", ["4 apples", "2 apples"], "4 apples", "4 comes after 2 when we count."],
      ["short", "Write the number that comes after 6.", null, "7", "Count up: 6, then 7."],
    ],
    "Use counters or fingers for children who need support. Watch for one-to-one counting (one number word per object).",
    "Exit ticket", "Say or circle your answer.",
    [
      ["multiple_choice", "Which number is bigger?", ["8", "3"], "8", "easy", "Comparing numbers"],
      ["short_answer", "How many fingers are on one hand?", null, "5", "easy", "Counting"],
      ["true_false", "The number after 9 is 10.", null, "True", "easy", "Number order"],
      ["multiple_choice", "Count: ● ● ● ●. How many?", ["3", "4"], "4", "easy", "Counting to 10"],
    ]),
  S("us", "1", "English Language Arts", "Short Vowel Sounds and Simple Sentences",
    "Read each word out loud. Fill in the missing short-vowel letter, then use the word in a short sentence.",
    [
      ["short", "c _ t (a small pet that says meow)", null, "a", "The word is 'cat' — short /a/ sound."],
      ["short", "b _ d (where you sleep)", null, "e", "The word is 'bed' — short /e/ sound."],
      ["short", "p _ g (a farm animal)", null, "i", "The word is 'pig' — short /i/ sound."],
      ["long", "Write a sentence using the word 'sun'.", null, "Answers vary, e.g. 'The sun is hot.'", "Rubric: capital letter at the start, the word 'sun' used correctly, a period at the end."],
    ],
    "Model blending sounds slowly. Accept phonetic spelling in the sentence as long as the target word is correct.",
    "Quick check", "Choose the best answer.",
    [
      ["multiple_choice", "Which word has the short /o/ sound?", ["dog", "day"], "dog", "easy", "Short vowels"],
      ["multiple_choice", "Which is a complete sentence?", ["The dog ran.", "the dog"], "The dog ran.", "medium", "Sentence structure"],
      ["true_false", "Every sentence begins with a capital letter.", null, "True", "easy", "Capitalization"],
      ["short_answer", "What short vowel is in the word 'hat'?", null, "a", "easy", "Short vowels"],
    ]),
  S("us", "2", "Mathematics", "Addition and Subtraction Within 100",
    "Solve each problem. Show your work using place value or a number line.",
    [
      ["calculation", "34 + 25 = ?", null, "59", "Add tens: 30 + 20 = 50. Add ones: 4 + 5 = 9. 50 + 9 = 59."],
      ["calculation", "72 − 40 = ?", null, "32", "Subtract the tens: 7 tens − 4 tens = 3 tens. Ones stay: 32."],
      ["calculation", "48 + 27 = ?", null, "75", "8 + 7 = 15 (regroup). 40 + 20 + 10 = 70. 70 + 5 = 75."],
      ["short", "Maria had 50 stickers and gave away 18. How many are left?", null, "32", "50 − 18: 50 − 10 = 40, 40 − 8 = 32."],
    ],
    "Encourage regrouping with base-ten blocks. Common error: forgetting to carry the regrouped ten.",
    "Exit ticket", "Solve and write your answer.",
    [
      ["short_answer", "26 + 13 = ?", null, "39", "easy", "Two-digit addition"],
      ["short_answer", "90 − 45 = ?", null, "45", "medium", "Two-digit subtraction"],
      ["multiple_choice", "Which sum needs regrouping?", ["23 + 14", "27 + 18"], "27 + 18", "medium", "Place value"],
      ["true_false", "Addition can be done in any order (3 + 5 = 5 + 3).", null, "True", "easy", "Commutative property"],
    ]),
  S("us", "3", "Mathematics", "Multiplication Facts and Equal Groups",
    "Draw equal groups where asked, then write and solve the multiplication sentence.",
    [
      ["calculation", "4 groups of 5 = ?", null, "20", "4 × 5 = 20. Skip count: 5, 10, 15, 20."],
      ["calculation", "6 × 3 = ?", null, "18", "6 threes: 3, 6, 9, 12, 15, 18."],
      ["short", "Write a multiplication sentence for 3 rows of 7 chairs.", null, "3 × 7 = 21", "3 rows, 7 in each row."],
      ["short", "There are 8 packs with 2 pencils each. How many pencils?", null, "16", "8 × 2 = 16."],
    ],
    "Connect multiplication to repeated addition and arrays. Target the ×2, ×5, ×10 facts first.",
    "Quick check", "Choose or write the answer.",
    [
      ["multiple_choice", "7 × 5 = ?", ["30", "35", "40"], "35", "easy", "Multiplication facts"],
      ["short_answer", "9 × 2 = ?", null, "18", "easy", "Multiplication facts"],
      ["true_false", "4 × 3 is the same as 3 × 4.", null, "True", "medium", "Commutative property"],
      ["short_answer", "How many legs on 5 dogs (4 legs each)?", null, "20", "medium", "Multiplication in context"],
    ]),
  S("us", "4", "English Language Arts", "Main Idea and Supporting Details",
    "Read the short paragraph, then answer the questions about its main idea and details.",
    [
      ["long", "In your own words, what is the main idea of a paragraph about how bees help plants grow?", null, "Answers vary: Bees are important because they help plants make new plants (pollination).", "Rubric: states one central idea in the student's own words, not just a copied sentence."],
      ["short", "Give one supporting detail an author might use for that main idea.", null, "Answers vary, e.g. 'Bees carry pollen from flower to flower.'", "Detail must clearly support the main idea."],
      ["multiple_choice", "The main idea of a paragraph is best described as…", ["the most important point", "the first word", "a fun fact"], "the most important point", "Main idea = the point the whole paragraph is about."],
      ["short", "What text feature often signals the main idea?", null, "The topic sentence (often the first sentence)", "Topic sentences frequently open a paragraph."],
    ],
    "Use a two-column organizer: main idea on the left, details on the right. Watch for students who choose an interesting detail as the main idea.",
    "Reading check", "Answer each question.",
    [
      ["multiple_choice", "A supporting detail…", ["tells more about the main idea", "changes the topic"], "tells more about the main idea", "medium", "Text structure"],
      ["true_false", "The main idea is always in the title.", null, "False", "medium", "Main idea"],
      ["short_answer", "What do we call the sentence that states the main idea?", null, "Topic sentence", "medium", "Text structure"],
      ["multiple_choice", "Best strategy to find the main idea?", ["Ask what the whole paragraph is mostly about", "Read only the last word"], "Ask what the whole paragraph is mostly about", "easy", "Comprehension strategy"],
    ]),
  S("us", "5", "Mathematics", "Adding and Subtracting Fractions",
    "Find a common denominator where needed, then add or subtract. Simplify your answer.",
    [
      ["calculation", "1/4 + 2/4 = ?", null, "3/4", "Same denominator: add numerators, 1 + 2 = 3."],
      ["calculation", "1/2 + 1/3 = ?", null, "5/6", "Common denominator 6: 3/6 + 2/6 = 5/6."],
      ["calculation", "5/6 − 1/3 = ?", null, "1/2", "1/3 = 2/6. 5/6 − 2/6 = 3/6 = 1/2."],
      ["short", "A recipe needs 3/4 cup of flour. You have 1/4 cup. How much more do you need?", null, "1/2 cup", "3/4 − 1/4 = 2/4 = 1/2."],
    ],
    "Use fraction bars for visualizing common denominators. Common error: adding denominators.",
    "Exit ticket", "Solve and simplify.",
    [
      ["short_answer", "2/5 + 1/5 = ?", null, "3/5", "easy", "Like denominators"],
      ["short_answer", "3/4 − 1/2 = ?", null, "1/4", "medium", "Unlike denominators"],
      ["true_false", "To add 1/3 + 1/6 you must first make the denominators the same.", null, "True", "medium", "Common denominators"],
      ["multiple_choice", "Which equals 1?", ["4/4", "3/4"], "4/4", "easy", "Fractions equal to a whole"],
    ]),
  S("us", "6", "Mathematics", "Ratios and Unit Rates",
    "Write each ratio, then find the unit rate (the amount for one).",
    [
      ["short", "A team wins 3 games for every 2 it loses. Write the ratio of wins to losses.", null, "3 to 2 (3:2)", "Order matters: wins first, then losses."],
      ["calculation", "12 apples cost $6. What is the price per apple?", null, "$0.50", "6 ÷ 12 = 0.5, so $0.50 each."],
      ["calculation", "A car travels 150 miles in 3 hours. What is the speed in miles per hour?", null, "50 mph", "150 ÷ 3 = 50."],
      ["short", "A smoothie uses 2 cups of fruit for every 1 cup of yogurt. How much fruit for 3 cups of yogurt?", null, "6 cups", "Ratio 2:1, so 3 × 2 = 6."],
    ],
    "Emphasize 'per one' language for unit rate. Link to division. Watch ratio order.",
    "Quick check", "Solve each problem.",
    [
      ["short_answer", "8 pencils for $2. Price per pencil?", null, "$0.25", "medium", "Unit rate"],
      ["multiple_choice", "The ratio 4:8 is the same as…", ["1:2", "2:1"], "1:2", "medium", "Equivalent ratios"],
      ["short_answer", "60 miles in 2 hours = ? mph", null, "30", "easy", "Rate"],
      ["true_false", "A unit rate always has 1 in the second quantity.", null, "True", "medium", "Unit rate"],
    ]),
  S("us", "7", "Mathematics", "Proportional Relationships and Percentages",
    "Solve using proportions or percent reasoning. Show your method.",
    [
      ["calculation", "What is 20% of 45?", null, "9", "20% = 0.20; 0.20 × 45 = 9."],
      ["calculation", "A shirt costs $40 and is 25% off. What is the sale price?", null, "$30", "25% of 40 = 10; 40 − 10 = 30."],
      ["short", "If 3 notebooks cost $9, how much do 7 notebooks cost?", null, "$21", "Unit price $3; 7 × 3 = 21."],
      ["calculation", "15 is what percent of 60?", null, "25%", "15/60 = 0.25 = 25%."],
    ],
    "Connect proportions, fractions, and percents. Common error: taking the percent of the wrong base.",
    "Exit ticket", "Solve and show your work.",
    [
      ["short_answer", "10% of 250 = ?", null, "25", "easy", "Percent of a number"],
      ["short_answer", "A $50 item is marked up 20%. New price?", null, "$60", "medium", "Percent increase"],
      ["multiple_choice", "Which is a proportional relationship?", ["y = 3x", "y = x + 3"], "y = 3x", "medium", "Proportional reasoning"],
      ["true_false", "50% off is the same as paying half price.", null, "True", "easy", "Percent"],
    ]),
  S("us", "8", "Mathematics", "Solving Linear Equations",
    "Solve for the variable. Show each step and check your answer.",
    [
      ["calculation", "Solve: 3x + 4 = 19", null, "x = 5", "3x = 15; x = 5. Check: 3(5)+4 = 19. ✓"],
      ["calculation", "Solve: 2(x − 3) = 10", null, "x = 8", "Distribute: 2x − 6 = 10; 2x = 16; x = 8."],
      ["calculation", "Solve: 5x − 7 = 2x + 8", null, "x = 5", "3x = 15; x = 5."],
      ["short", "A number tripled and increased by 4 is 25. What is the number?", null, "7", "3n + 4 = 25; 3n = 21; n = 7."],
    ],
    "Stress doing the same operation to both sides. Common error: distributing only to the first term.",
    "Quick check", "Solve each equation.",
    [
      ["short_answer", "x + 9 = 20. x = ?", null, "11", "easy", "One-step equations"],
      ["short_answer", "4x = 36. x = ?", null, "9", "easy", "One-step equations"],
      ["short_answer", "2x + 5 = 17. x = ?", null, "6", "medium", "Two-step equations"],
      ["true_false", "You can add the same number to both sides of an equation without changing the solution.", null, "True", "medium", "Properties of equality"],
    ]),
  S("us", "9", "English Language Arts", "Analyzing Theme in a Short Story",
    "Answer using evidence. A theme is a message about life the story explores.",
    [
      ["long", "State one theme of a story in which a character learns that honesty repairs a broken friendship. Support it with a detail.", null, "Answers vary: Theme — honesty can rebuild trust. Detail — the character admits the lie and the friend forgives them.", "Rubric: a theme stated as a full idea (not one word), plus one relevant textual detail."],
      ["multiple_choice", "A theme is best described as…", ["a message about life", "the setting", "a character's name"], "a message about life", "Theme = the underlying message."],
      ["short", "How is a theme different from a topic?", null, "A topic is what the story is about (e.g. 'friendship'); a theme is what it says about that topic (e.g. 'true friends forgive').", "Topic = subject; theme = the claim/insight."],
      ["long", "Explain how a character's change can reveal a story's theme.", null, "Answers vary: as the character grows or learns a lesson, the author shows the message they want readers to take away.", "Rubric: links character change to the message; uses reasoning."],
    ],
    "Push students beyond one-word themes ('love') to full statements ('sacrifice can be an act of love'). Require textual evidence.",
    "Reading check", "Answer each question.",
    [
      ["multiple_choice", "'Perseverance leads to success' is a…", ["theme", "topic"], "theme", "medium", "Theme vs topic"],
      ["true_false", "A story can have more than one theme.", null, "True", "easy", "Theme"],
      ["short_answer", "What kind of evidence supports a theme claim?", null, "Details/quotations from the text", "medium", "Textual evidence"],
      ["multiple_choice", "The best theme statement is…", ["a complete idea about life", "a single word"], "a complete idea about life", "easy", "Theme"],
    ]),
  S("us", "10", "Mathematics", "Quadratic Functions and Factoring",
    "Factor and solve where possible. Show your steps.",
    [
      ["calculation", "Factor: x² + 5x + 6", null, "(x + 2)(x + 3)", "Two numbers multiplying to 6 and adding to 5: 2 and 3."],
      ["calculation", "Solve: x² − 9 = 0", null, "x = 3 or x = −3", "Difference of squares: (x−3)(x+3)=0."],
      ["calculation", "Solve: x² + 5x + 6 = 0", null, "x = −2 or x = −3", "Factors (x+2)(x+3)=0."],
      ["short", "What are the x-intercepts of y = (x − 4)(x + 1)?", null, "x = 4 and x = −1", "Set each factor to 0."],
    ],
    "Review the zero-product property. Common error: sign mistakes when the constant is negative.",
    "Exit ticket", "Solve or factor.",
    [
      ["short_answer", "Factor x² − 16.", null, "(x − 4)(x + 4)", "medium", "Difference of squares"],
      ["multiple_choice", "The graph of a quadratic is a…", ["parabola", "straight line"], "parabola", "easy", "Function families"],
      ["short_answer", "Solve x² = 25.", null, "x = 5 or x = −5", "medium", "Square roots"],
      ["true_false", "A quadratic can have two real solutions.", null, "True", "easy", "Quadratics"],
    ]),
  S("us", "11", "English Language Arts", "Rhetorical Analysis of Argument",
    "Analyze how a writer persuades. Use the terms ethos, pathos, and logos.",
    [
      ["short", "Which appeal relies on logic and evidence?", null, "Logos", "Logos = reasoning, data, facts."],
      ["short", "Which appeal relies on emotion?", null, "Pathos", "Pathos = feelings of the audience."],
      ["long", "Identify one rhetorical strategy a writer might use to build credibility (ethos) and explain its effect.", null, "Answers vary: citing their experience or expert sources builds trust so the audience takes the claim seriously.", "Rubric: names a strategy tied to ethos and explains the effect on the audience."],
      ["long", "How does a counterargument strengthen an argument?", null, "Answers vary: addressing the other side shows fairness and makes the writer's position more convincing.", "Rubric: explains the persuasive purpose of acknowledging counterpoints."],
    ],
    "Have students annotate a real op-ed for ethos/pathos/logos. Push for analysis of effect, not just labeling.",
    "Quick check", "Choose the best answer.",
    [
      ["multiple_choice", "'9 out of 10 doctors recommend…' is an appeal to…", ["logos", "pathos"], "logos", "medium", "Rhetorical appeals"],
      ["multiple_choice", "A sad personal story is an appeal to…", ["pathos", "ethos"], "pathos", "easy", "Rhetorical appeals"],
      ["true_false", "Ethos is about the speaker's credibility.", null, "True", "easy", "Rhetorical appeals"],
      ["short_answer", "Name the appeal based on logic and reasoning.", null, "Logos", "medium", "Rhetorical appeals"],
    ]),
  S("us", "12", "Mathematics", "Limits and the Idea of a Derivative",
    "Answer conceptually and compute simple limits and rates of change.",
    [
      ["calculation", "Evaluate the limit as x → 2 of (x² − 4)/(x − 2).", null, "4", "Factor: (x−2)(x+2)/(x−2) = x+2 → 4."],
      ["short", "What does a derivative measure?", null, "The instantaneous rate of change (slope of the tangent line).", "Derivative = slope at a point."],
      ["calculation", "Find the average rate of change of f(x) = x² on [1, 3].", null, "4", "(9 − 1)/(3 − 1) = 8/2 = 4."],
      ["short", "As h → 0, [f(x+h) − f(x)]/h approaches what?", null, "The derivative f′(x).", "This is the definition of the derivative."],
    ],
    "Bridge from average rate of change (secant) to instantaneous (tangent). Common error: plugging in the value that makes the denominator 0 without simplifying.",
    "Exit ticket", "Solve and explain.",
    [
      ["short_answer", "Limit as x → 0 of (3x)/x = ?", null, "3", "medium", "Limits"],
      ["multiple_choice", "The derivative gives the…", ["slope of the tangent line", "area under the curve"], "slope of the tangent line", "medium", "Derivative concept"],
      ["true_false", "Average rate of change is the slope of a secant line.", null, "True", "easy", "Rates of change"],
      ["short_answer", "For f(x)=x², the average rate of change on [2,4] is?", null, "6", "hard", "Rates of change"],
    ]),
];

// ── United Kingdom (Reception–Year 13) ───────────────────────────────────────
const UK: Spec[] = [
  S("uk", "Reception", "Mathematics", "Numbers to 10 and Simple Patterns",
    "Count the pictures and write the number. Continue the pattern.",
    [
      ["short", "How many ducks? 🦆 🦆 🦆 🦆", null, "4", "Count each duck once."],
      ["short", "What number comes after 5?", null, "6", "Count on: 5, 6."],
      ["multiple_choice", "Which set has fewer?", ["3 cars", "5 cars"], "3 cars", "3 is less than 5."],
      ["short", "Continue: red, blue, red, blue, ___", null, "red", "The pattern repeats red, blue."],
    ],
    "Use practical objects. Focus on stable counting order and one-to-one correspondence.",
    "Quick check", "Point to or say your answer.",
    [
      ["multiple_choice", "Which is more?", ["7", "2"], "7", "easy", "Comparing numbers"],
      ["short_answer", "What comes before 4?", null, "3", "easy", "Number order"],
      ["true_false", "The number 10 has two digits.", null, "True", "easy", "Number sense"],
      ["multiple_choice", "🔺 🔻 🔺 🔻 ___", ["🔺", "🔻"], "🔺", "easy", "Patterns"],
    ]),
  S("uk", "Y1", "English", "Phonics: Digraphs (sh, ch, th)",
    "Say each word. Write the digraph that is missing.",
    [
      ["short", "___ip (a boat)", null, "sh", "The word is 'ship'."],
      ["short", "___in (part of your face)", null, "ch", "The word is 'chin'."],
      ["short", "ba___ (you wash in it)", null, "th", "The word is 'bath'."],
      ["long", "Write a sentence with the word 'fish'.", null, "Answers vary, e.g. 'The fish can swim.'", "Rubric: capital letter, target word used, full stop."],
    ],
    "Model pure sounds. Accept phonetically plausible spelling elsewhere in the sentence.",
    "Quick check", "Choose the best answer.",
    [
      ["multiple_choice", "Which word has 'sh'?", ["shop", "top"], "shop", "easy", "Digraphs"],
      ["short_answer", "What two letters make the sound at the start of 'chair'?", null, "ch", "easy", "Digraphs"],
      ["true_false", "'th' is one sound made by two letters.", null, "True", "medium", "Phonics"],
      ["multiple_choice", "Complete: 'The ___ip sailed.'", ["sh", "ch"], "sh", "easy", "Digraphs"],
    ]),
  S("uk", "Y2", "Mathematics", "Addition and Subtraction to 100",
    "Work out each calculation. Use a number line or partitioning.",
    [
      ["calculation", "23 + 15 = ?", null, "38", "20 + 10 = 30; 3 + 5 = 8; 38."],
      ["calculation", "60 − 24 = ?", null, "36", "60 − 20 = 40; 40 − 4 = 36."],
      ["calculation", "38 + 27 = ?", null, "65", "8 + 7 = 15 (regroup); 30 + 20 + 10 = 60; 65."],
      ["short", "Sam has 45p and spends 18p. How much is left?", null, "27p", "45 − 18 = 27."],
    ],
    "Use partitioning into tens and ones. Watch for exchange/regrouping errors.",
    "Exit ticket", "Solve each one.",
    [
      ["short_answer", "34 + 12 = ?", null, "46", "easy", "Two-digit addition"],
      ["short_answer", "80 − 35 = ?", null, "45", "medium", "Two-digit subtraction"],
      ["true_false", "Addition can be done in any order.", null, "True", "easy", "Commutativity"],
      ["multiple_choice", "Which needs exchanging?", ["25 + 13", "26 + 19"], "26 + 19", "medium", "Place value"],
    ]),
  S("uk", "Y3", "Mathematics", "Multiplication and Division Facts",
    "Recall and use the 3, 4 and 8 times tables.",
    [
      ["calculation", "4 × 6 = ?", null, "24", "Four sixes: 6, 12, 18, 24."],
      ["calculation", "24 ÷ 3 = ?", null, "8", "3 × 8 = 24."],
      ["calculation", "8 × 5 = ?", null, "40", "Eight fives: 5,10,...,40."],
      ["short", "Share 32 sweets equally between 4 children. How many each?", null, "8", "32 ÷ 4 = 8."],
    ],
    "Link multiplication and division as inverse operations. Practise recall for fluency.",
    "Quick check", "Answer each.",
    [
      ["short_answer", "3 × 7 = ?", null, "21", "easy", "Times tables"],
      ["short_answer", "36 ÷ 4 = ?", null, "9", "medium", "Division facts"],
      ["true_false", "8 × 4 is the same as 4 × 8.", null, "True", "easy", "Commutativity"],
      ["short_answer", "How many wheels on 4 cars (4 wheels each)?", null, "16", "medium", "Multiplication in context"],
    ]),
  S("uk", "Y4", "English", "Fronted Adverbials and Punctuation",
    "A fronted adverbial starts a sentence and needs a comma after it.",
    [
      ["short", "Add the missing comma: 'After lunch we played outside.'", null, "After lunch, we played outside.", "Comma follows the fronted adverbial."],
      ["short", "Underline the fronted adverbial: 'Quietly, the cat crept away.'", null, "Quietly", "It tells how and opens the sentence."],
      ["long", "Write a sentence that begins with a fronted adverbial of time.", null, "Answers vary, e.g. 'Later that day, the rain stopped.'", "Rubric: opens with a time phrase, comma after it, complete sentence."],
      ["multiple_choice", "Which is a fronted adverbial?", ["Suddenly,", "the dog"], "Suddenly,", "It modifies the sentence and comes first."],
    ],
    "Show adverbials of time, place and manner. Common error: missing the comma.",
    "Quick check", "Choose the best answer.",
    [
      ["multiple_choice", "Where does the comma go? 'In the morning ___ we left.'", ["after 'morning'", "after 'we'"], "after 'morning'", "medium", "Punctuation"],
      ["true_false", "A fronted adverbial can describe when, where or how.", null, "True", "easy", "Grammar"],
      ["short_answer", "Name the punctuation mark that follows a fronted adverbial.", null, "Comma", "easy", "Punctuation"],
      ["multiple_choice", "Pick the fronted adverbial of place.", ["Near the river,", "ran quickly"], "Near the river,", "medium", "Grammar"],
    ]),
  S("uk", "Y5", "Mathematics", "Fractions: Adding and Comparing",
    "Add and compare fractions. Simplify where you can.",
    [
      ["calculation", "1/5 + 2/5 = ?", null, "3/5", "Same denominator: add numerators."],
      ["calculation", "1/2 + 1/4 = ?", null, "3/4", "1/2 = 2/4; 2/4 + 1/4 = 3/4."],
      ["multiple_choice", "Which is larger?", ["3/4", "2/3"], "3/4", "3/4 = 0.75, 2/3 ≈ 0.67."],
      ["short", "Simplify 6/8.", null, "3/4", "Divide top and bottom by 2."],
    ],
    "Use fraction walls to compare. Common error: adding denominators.",
    "Exit ticket", "Solve and simplify.",
    [
      ["short_answer", "2/6 + 1/6 = ?", null, "3/6 (or 1/2)", "easy", "Like denominators"],
      ["short_answer", "Simplify 4/10.", null, "2/5", "medium", "Simplifying"],
      ["true_false", "1/3 is greater than 1/4.", null, "True", "medium", "Comparing fractions"],
      ["multiple_choice", "Which equals a whole?", ["5/5", "4/5"], "5/5", "easy", "Fractions"],
    ]),
  S("uk", "Y6", "Mathematics", "Ratio, Proportion and Percentages",
    "Solve ratio and percentage problems. Show your reasoning.",
    [
      ["calculation", "Find 15% of 200.", null, "30", "10% = 20, 5% = 10, total 30."],
      ["short", "Simplify the ratio 10:15.", null, "2:3", "Divide both by 5."],
      ["short", "A recipe uses flour and sugar in the ratio 3:1. For 12 cups of flour, how much sugar?", null, "4 cups", "12 ÷ 3 = 4 → 1 × 4 = 4."],
      ["calculation", "A £60 coat is reduced by 25%. What is the new price?", null, "£45", "25% of 60 = 15; 60 − 15 = 45."],
    ],
    "Connect fractions, decimals and percentages. Watch ratio order and the base of a percentage.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "20% of 150 = ?", null, "30", "easy", "Percentages"],
      ["multiple_choice", "6:9 simplifies to…", ["2:3", "3:2"], "2:3", "medium", "Ratio"],
      ["short_answer", "Share £40 in the ratio 3:1. Larger share?", null, "£30", "hard", "Ratio sharing"],
      ["true_false", "50% is the same as 1/2.", null, "True", "easy", "Percentages"],
    ]),
  S("uk", "Y7", "Mathematics", "Negative Numbers and Order of Operations",
    "Use BIDMAS and the rules for negative numbers.",
    [
      ["calculation", "−5 + 8 = ?", null, "3", "Start at −5, count up 8."],
      ["calculation", "6 + 2 × 3 = ?", null, "12", "Multiply first: 2 × 3 = 6; 6 + 6 = 12."],
      ["calculation", "(4 + 2)² − 10 = ?", null, "26", "Brackets: 6; 6² = 36; 36 − 10 = 26."],
      ["short", "The temperature is −3°C and rises by 7°C. What is it now?", null, "4°C", "−3 + 7 = 4."],
    ],
    "Emphasise BIDMAS order. Common error: adding before multiplying.",
    "Exit ticket", "Work each out.",
    [
      ["short_answer", "−4 − 3 = ?", null, "−7", "easy", "Negative numbers"],
      ["short_answer", "10 − 2 × 4 = ?", null, "2", "medium", "Order of operations"],
      ["true_false", "Subtracting a negative is the same as adding.", null, "True", "medium", "Negative numbers"],
      ["multiple_choice", "Which do you do first in 3 + 4 × 2?", ["4 × 2", "3 + 4"], "4 × 2", "easy", "BIDMAS"],
    ]),
  S("uk", "Y8", "Science", "The Particle Model of Matter",
    "Use the particle model to explain states of matter.",
    [
      ["multiple_choice", "In which state are particles most tightly packed?", ["Solid", "Gas"], "Solid", "Solids have fixed, close-packed particles."],
      ["short", "Name the change of state from liquid to gas.", null, "Evaporation (or boiling)", "Liquid → gas."],
      ["long", "Explain, using particles, why a gas fills its container.", null, "Answers vary: gas particles move quickly in all directions and are far apart, so they spread to fill the space.", "Rubric: refers to particle movement and spacing."],
      ["short", "What happens to particle movement when a solid is heated?", null, "They vibrate/move faster (gain energy)", "Heating adds energy."],
    ],
    "Link temperature to particle energy. Common misconception: particles themselves expand when heated.",
    "Quick check", "Choose or answer.",
    [
      ["multiple_choice", "Gas → liquid is called…", ["condensation", "melting"], "condensation", "medium", "States of matter"],
      ["true_false", "Particles in a gas are far apart.", null, "True", "easy", "Particle model"],
      ["short_answer", "Solid → liquid is called…?", null, "Melting", "easy", "Changes of state"],
      ["multiple_choice", "Heating a substance gives its particles more…", ["energy", "mass"], "energy", "medium", "Particle energy"],
    ]),
  S("uk", "Y9", "Mathematics", "Linear Equations and Graphs",
    "Solve equations and interpret straight-line graphs (y = mx + c).",
    [
      ["calculation", "Solve: 4x − 5 = 11", null, "x = 4", "4x = 16; x = 4."],
      ["short", "In y = 3x + 2, what is the gradient?", null, "3", "Gradient m is the coefficient of x."],
      ["short", "In y = 3x + 2, what is the y-intercept?", null, "2", "c = 2, where the line crosses the y-axis."],
      ["calculation", "Solve: 2(x + 4) = 18", null, "x = 5", "2x + 8 = 18; 2x = 10; x = 5."],
    ],
    "Connect equations and graphs. Common error: confusing gradient and intercept.",
    "Exit ticket", "Solve/interpret.",
    [
      ["short_answer", "3x + 6 = 21. x = ?", null, "5", "easy", "Linear equations"],
      ["multiple_choice", "In y = 2x − 1, the gradient is…", ["2", "−1"], "2", "medium", "Graphs"],
      ["true_false", "A larger gradient means a steeper line.", null, "True", "medium", "Graphs"],
      ["short_answer", "Where does y = x + 4 cross the y-axis?", null, "(0, 4)", "medium", "Graphs"],
    ]),
  S("uk", "Y10", "English Literature", "Analysing Language and Structure",
    "Answer using PEE (Point, Evidence, Explanation).",
    [
      ["short", "What does the term 'metaphor' mean?", null, "A comparison saying one thing IS another (not using 'like'/'as').", "Direct comparison."],
      ["short", "Name the technique in 'the wind whispered'.", null, "Personification", "Gives human action to the wind."],
      ["long", "Using PEE, analyse how a writer creates tension in a scene of your choice.", null, "Answers vary: Point (the writer builds tension), Evidence (a short quotation), Explanation (how the language/structure affects the reader).", "Rubric: clear point, embedded quotation, explanation of effect on reader."],
      ["long", "How can sentence structure affect a reader's response?", null, "Answers vary: short sentences can speed up pace and create urgency; long sentences can slow it down.", "Rubric: links a structural choice to reader effect."],
    ],
    "Insist on embedded quotations and analysis of effect, not feature-spotting.",
    "Quick check", "Choose or answer.",
    [
      ["multiple_choice", "'Time is a thief' is a…", ["metaphor", "simile"], "metaphor", "medium", "Language techniques"],
      ["short_answer", "A comparison using 'like' or 'as' is a…?", null, "Simile", "easy", "Language techniques"],
      ["true_false", "PEE stands for Point, Evidence, Explanation.", null, "True", "easy", "Analytical writing"],
      ["multiple_choice", "Repeating a sound at the start of words is…", ["alliteration", "rhyme"], "alliteration", "medium", "Language techniques"],
    ]),
  S("uk", "Y11", "Mathematics", "Quadratics and the Quadratic Formula",
    "Solve quadratic equations by factorising or using the formula.",
    [
      ["calculation", "Factorise: x² + 7x + 12", null, "(x + 3)(x + 4)", "3 × 4 = 12, 3 + 4 = 7."],
      ["calculation", "Solve: x² − x − 6 = 0", null, "x = 3 or x = −2", "(x − 3)(x + 2) = 0."],
      ["short", "Write the quadratic formula.", null, "x = (−b ± √(b² − 4ac)) / 2a", "Standard GCSE formula."],
      ["calculation", "For x² + 4x + 4 = 0, how many real roots?", null, "One (repeated) root, x = −2", "Discriminant = 0."],
    ],
    "Discuss the discriminant b² − 4ac and what it reveals about roots.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "Factorise x² + 5x + 6.", null, "(x + 2)(x + 3)", "medium", "Factorising"],
      ["short_answer", "Solve x² = 49.", null, "x = 7 or x = −7", "easy", "Quadratics"],
      ["true_false", "If b² − 4ac < 0 there are no real roots.", null, "True", "hard", "Discriminant"],
      ["multiple_choice", "A quadratic graph is a…", ["parabola", "line"], "parabola", "easy", "Graphs"],
    ]),
  S("uk", "Y12", "Mathematics", "Differentiation (Introduction)",
    "Differentiate polynomials and interpret the result (AS level).",
    [
      ["calculation", "Differentiate y = x³.", null, "dy/dx = 3x²", "Bring down the power, reduce by one."],
      ["calculation", "Differentiate y = 5x² − 3x + 2.", null, "dy/dx = 10x − 3", "Term by term."],
      ["short", "What does dy/dx represent?", null, "The gradient of the curve / rate of change.", "Slope of the tangent."],
      ["calculation", "Find the gradient of y = x² at x = 3.", null, "6", "dy/dx = 2x; at x = 3, 2(3) = 6."],
    ],
    "Reinforce the power rule. Common error: forgetting the derivative of a constant is 0.",
    "Quick check", "Differentiate/interpret.",
    [
      ["short_answer", "Differentiate y = x².", null, "2x", "easy", "Power rule"],
      ["short_answer", "Differentiate y = 4x.", null, "4", "easy", "Power rule"],
      ["true_false", "The derivative of a constant is 0.", null, "True", "medium", "Differentiation"],
      ["short_answer", "Gradient of y = x³ at x = 2?", null, "12", "hard", "Differentiation"],
    ]),
  S("uk", "Y13", "Mathematics", "Integration (Introduction)",
    "Integrate polynomials and evaluate simple definite integrals (A level).",
    [
      ["calculation", "Integrate ∫ 2x dx.", null, "x² + c", "Raise power by one, divide by new power."],
      ["calculation", "Integrate ∫ (3x² + 1) dx.", null, "x³ + x + c", "Term by term; don't forget + c."],
      ["short", "Why do we add '+ c' for an indefinite integral?", null, "Because the constant term disappears when differentiating, so it is unknown.", "Family of curves."],
      ["calculation", "Evaluate ∫ from 0 to 2 of 2x dx.", null, "4", "[x²] from 0 to 2 = 4 − 0 = 4."],
    ],
    "Link integration as the reverse of differentiation. Common error: omitting + c.",
    "Exit ticket", "Integrate/evaluate.",
    [
      ["short_answer", "∫ 4x³ dx = ?", null, "x⁴ + c", "medium", "Integration"],
      ["short_answer", "∫ 6x dx = ?", null, "3x² + c", "easy", "Integration"],
      ["true_false", "A definite integral gives the area under a curve.", null, "True", "medium", "Definite integrals"],
      ["short_answer", "∫ from 0 to 3 of 2 dx = ?", null, "6", "medium", "Definite integrals"],
    ]),
];

// ── Europe / IB (PYP 1 – DP Year 2) ──────────────────────────────────────────
const EU: Spec[] = [
  S("europe", "PYP1", "Mathematics", "Counting and Number Recognition to 10",
    "Count and write the number. Match the amount that is the same.",
    [
      ["short", "How many apples? 🍎🍎🍎", null, "3", "Count each apple once."],
      ["short", "Write the number after 7.", null, "8", "Count on from 7."],
      ["multiple_choice", "Which shows 5?", ["●●●●●", "●●●"], "●●●●●", "Five dots."],
      ["short", "Which is fewer: 2 or 6?", null, "2", "2 is less than 6."],
    ],
    "Use manipulatives. Focus on one-to-one correspondence.",
    "Quick check", "Say your answer.",
    [
      ["multiple_choice", "Which is bigger?", ["9", "4"], "9", "easy", "Comparing numbers"],
      ["short_answer", "What comes before 6?", null, "5", "easy", "Number order"],
      ["true_false", "Ten is more than five.", null, "True", "easy", "Number sense"],
      ["short_answer", "Count: ●●●●. How many?", null, "4", "easy", "Counting"],
    ]),
  S("europe", "PYP2", "English", "Sight Words and Simple Sentences",
    "Read the sight words. Complete each sentence.",
    [
      ["short", "Complete: 'I ___ happy.' (am/is)", null, "am", "'I am' is correct."],
      ["short", "Complete: 'The dog ___ big.' (am/is)", null, "is", "'The dog is' is correct."],
      ["multiple_choice", "Which is a sight word?", ["the", "elephant"], "the", "'the' is a common sight word."],
      ["long", "Write a sentence using the word 'we'.", null, "Answers vary, e.g. 'We like to play.'", "Rubric: capital letter, target word, full stop."],
    ],
    "Practise high-frequency words for automatic recognition.",
    "Quick check", "Choose the best word.",
    [
      ["multiple_choice", "'She ___ running.' ", ["is", "am"], "is", "easy", "Subject–verb"],
      ["true_false", "A sentence needs a full stop at the end.", null, "True", "easy", "Punctuation"],
      ["short_answer", "Write the sight word that means the opposite of 'no'.", null, "yes", "easy", "Sight words"],
      ["multiple_choice", "Pick the sentence.", ["We ran home.", "run home"], "We ran home.", "medium", "Sentences"],
    ]),
  S("europe", "PYP3", "Mathematics", "Addition and Subtraction Within 100",
    "Solve using number bonds or a number line.",
    [
      ["calculation", "27 + 16 = ?", null, "43", "7 + 6 = 13 (regroup); 20 + 10 + 10 = 40; 43."],
      ["calculation", "50 − 23 = ?", null, "27", "50 − 20 = 30; 30 − 3 = 27."],
      ["short", "There are 34 birds. 12 fly away. How many remain?", null, "22", "34 − 12 = 22."],
      ["calculation", "18 + 18 = ?", null, "36", "Double 18: 36."],
    ],
    "Encourage mental partitioning strategies.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "25 + 25 = ?", null, "50", "easy", "Addition"],
      ["short_answer", "60 − 15 = ?", null, "45", "medium", "Subtraction"],
      ["true_false", "13 + 20 = 33.", null, "True", "easy", "Addition"],
      ["multiple_choice", "Which needs regrouping?", ["24 + 15", "28 + 17"], "28 + 17", "medium", "Place value"],
    ]),
  S("europe", "PYP4", "Mathematics", "Multiplication and Times Tables",
    "Recall multiplication facts and solve word problems.",
    [
      ["calculation", "6 × 7 = ?", null, "42", "Six sevens: 42."],
      ["calculation", "9 × 4 = ?", null, "36", "Nine fours: 36."],
      ["short", "A box holds 8 crayons. How many in 5 boxes?", null, "40", "8 × 5 = 40."],
      ["calculation", "48 ÷ 6 = ?", null, "8", "6 × 8 = 48."],
    ],
    "Build fluency with the full multiplication grid.",
    "Quick check", "Answer each.",
    [
      ["short_answer", "7 × 8 = ?", null, "56", "medium", "Times tables"],
      ["short_answer", "45 ÷ 5 = ?", null, "9", "medium", "Division"],
      ["true_false", "6 × 9 = 54.", null, "True", "easy", "Times tables"],
      ["multiple_choice", "Which equals 24?", ["6 × 4", "6 × 5"], "6 × 4", "easy", "Times tables"],
    ]),
  S("europe", "PYP5", "Mathematics", "Fractions, Decimals and Percentages",
    "Convert between fractions, decimals and percentages.",
    [
      ["short", "Write 1/2 as a decimal.", null, "0.5", "1 ÷ 2 = 0.5."],
      ["short", "Write 0.25 as a percentage.", null, "25%", "0.25 × 100."],
      ["short", "Write 3/4 as a percentage.", null, "75%", "3/4 = 0.75 = 75%."],
      ["calculation", "Find 10% of 80.", null, "8", "80 ÷ 10 = 8."],
    ],
    "Use a triple number line linking fractions, decimals and percentages.",
    "Exit ticket", "Convert/solve.",
    [
      ["short_answer", "1/4 as a decimal?", null, "0.25", "easy", "Conversions"],
      ["short_answer", "50% as a fraction?", null, "1/2", "easy", "Conversions"],
      ["true_false", "0.5 = 50%.", null, "True", "easy", "Conversions"],
      ["short_answer", "20% of 60 = ?", null, "12", "medium", "Percentages"],
    ]),
  S("europe", "MYP1", "Mathematics", "Integers and Order of Operations",
    "Apply the order of operations and integer rules.",
    [
      ["calculation", "−7 + 12 = ?", null, "5", "Count up from −7 by 12."],
      ["calculation", "8 + 4 × 2 = ?", null, "16", "Multiply first: 4 × 2 = 8; 8 + 8 = 16."],
      ["calculation", "(5 − 8) × 3 = ?", null, "−9", "Brackets: −3; −3 × 3 = −9."],
      ["short", "A diver at −15 m rises 9 m. What is the new depth?", null, "−6 m", "−15 + 9 = −6."],
    ],
    "Reinforce operations order and integer sign rules.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "−5 − 6 = ?", null, "−11", "easy", "Integers"],
      ["short_answer", "12 − 3 × 2 = ?", null, "6", "medium", "Order of operations"],
      ["true_false", "A negative times a negative is positive.", null, "True", "medium", "Integer rules"],
      ["multiple_choice", "First step in 2 + 6 ÷ 3?", ["6 ÷ 3", "2 + 6"], "6 ÷ 3", "easy", "Order of operations"],
    ]),
  S("europe", "MYP2", "Sciences", "Cells and Living Systems",
    "Describe the basic structure of cells.",
    [
      ["multiple_choice", "Which part controls the cell's activities?", ["Nucleus", "Cell wall"], "Nucleus", "The nucleus holds genetic information."],
      ["short", "Name one part found in a plant cell but not an animal cell.", null, "Cell wall (or chloroplast/large vacuole)", "Plant-specific structures."],
      ["long", "Explain why cells are called the 'building blocks of life'.", null, "Answers vary: all living things are made of one or more cells, which carry out the processes of life.", "Rubric: refers to cells as the basic unit of living things."],
      ["short", "What does the cell membrane do?", null, "Controls what enters and leaves the cell.", "Selective barrier."],
    ],
    "Use labelled diagrams to compare plant and animal cells.",
    "Quick check", "Choose or answer.",
    [
      ["multiple_choice", "Photosynthesis happens in the…", ["chloroplast", "nucleus"], "chloroplast", "medium", "Cell biology"],
      ["true_false", "Animal cells have a cell wall.", null, "False", "easy", "Cell biology"],
      ["short_answer", "Which structure stores genetic material?", null, "Nucleus", "easy", "Cell biology"],
      ["multiple_choice", "The jelly-like substance in a cell is the…", ["cytoplasm", "membrane"], "cytoplasm", "medium", "Cell biology"],
    ]),
  S("europe", "MYP3", "Mathematics", "Linear Equations and Graphs",
    "Solve linear equations and read straight-line graphs.",
    [
      ["calculation", "Solve: 5x − 3 = 22", null, "x = 5", "5x = 25; x = 5."],
      ["short", "In y = 2x + 1, state the gradient and y-intercept.", null, "Gradient 2, y-intercept 1", "y = mx + c."],
      ["calculation", "Solve: 3(x − 2) = 9", null, "x = 5", "3x − 6 = 9; 3x = 15; x = 5."],
      ["short", "Does the point (2, 5) lie on y = 2x + 1?", null, "Yes", "2(2) + 1 = 5. ✓"],
    ],
    "Link algebraic and graphical representations.",
    "Exit ticket", "Solve/interpret.",
    [
      ["short_answer", "4x + 2 = 18. x = ?", null, "4", "easy", "Linear equations"],
      ["multiple_choice", "Gradient of y = 3x − 4?", ["3", "−4"], "3", "medium", "Graphs"],
      ["true_false", "The y-intercept is where x = 0.", null, "True", "medium", "Graphs"],
      ["short_answer", "Solve 2x − 7 = 5.", null, "6", "medium", "Linear equations"],
    ]),
  S("europe", "MYP4", "Mathematics", "Quadratics and Factorising",
    "Factorise and solve quadratic equations.",
    [
      ["calculation", "Factorise: x² + 6x + 8", null, "(x + 2)(x + 4)", "2 × 4 = 8, 2 + 4 = 6."],
      ["calculation", "Solve: x² − 5x + 6 = 0", null, "x = 2 or x = 3", "(x − 2)(x − 3) = 0."],
      ["short", "State the roots of y = (x − 1)(x + 5).", null, "x = 1 and x = −5", "Set each factor to zero."],
      ["calculation", "Solve: x² − 16 = 0", null, "x = 4 or x = −4", "Difference of squares."],
    ],
    "Use the zero-product property. Watch signs.",
    "Quick check", "Factorise/solve.",
    [
      ["short_answer", "Factorise x² + 3x.", null, "x(x + 3)", "easy", "Common factors"],
      ["short_answer", "Solve x² = 36.", null, "x = 6 or x = −6", "easy", "Quadratics"],
      ["true_false", "A parabola can cross the x-axis twice.", null, "True", "medium", "Graphs"],
      ["multiple_choice", "Factorised form of x² − 9?", ["(x−3)(x+3)", "(x−9)(x+1)"], "(x−3)(x+3)", "medium", "Difference of squares"],
    ]),
  S("europe", "MYP5", "Mathematics", "Trigonometry (Right-Angled Triangles)",
    "Use SOH-CAH-TOA to find missing sides and angles.",
    [
      ["short", "Which ratio uses opposite and hypotenuse?", null, "Sine (sin)", "SOH."],
      ["calculation", "In a right triangle, opposite = 3, hypotenuse = 6. Find sin θ.", null, "0.5", "sin θ = 3/6 = 0.5."],
      ["short", "If sin θ = 0.5, what is θ (to the nearest degree)?", null, "30°", "sin⁻¹(0.5) = 30°."],
      ["calculation", "Adjacent = 4, opposite = 3. Find tan θ.", null, "0.75", "tan θ = 3/4 = 0.75."],
    ],
    "Label sides relative to the angle. Common error: mixing adjacent and opposite.",
    "Exit ticket", "Solve each.",
    [
      ["multiple_choice", "cos θ uses…", ["adjacent/hypotenuse", "opposite/adjacent"], "adjacent/hypotenuse", "medium", "Trig ratios"],
      ["short_answer", "tan θ = opposite / ?", null, "adjacent", "easy", "Trig ratios"],
      ["true_false", "The hypotenuse is the longest side of a right triangle.", null, "True", "easy", "Right triangles"],
      ["short_answer", "sin 90° = ?", null, "1", "hard", "Trig values"],
    ]),
  S("europe", "DP1", "Mathematics", "Functions and Graphs",
    "Work with functions, domain and composite functions.",
    [
      ["calculation", "If f(x) = 2x + 3, find f(4).", null, "11", "2(4) + 3 = 11."],
      ["calculation", "If f(x) = x² and g(x) = x + 1, find f(g(2)).", null, "9", "g(2) = 3; f(3) = 9."],
      ["short", "State the domain of f(x) = 1/x.", null, "All real x except x = 0", "Cannot divide by zero."],
      ["short", "What is the inverse operation used to find f⁻¹ of f(x) = x + 5?", null, "Subtract 5: f⁻¹(x) = x − 5", "Undo the +5."],
    ],
    "Distinguish f(g(x)) from g(f(x)). Discuss domain restrictions.",
    "Quick check", "Evaluate/answer.",
    [
      ["short_answer", "f(x) = 3x − 1, find f(2).", null, "5", "easy", "Functions"],
      ["multiple_choice", "Domain of f(x) = √x is…", ["x ≥ 0", "all real x"], "x ≥ 0", "medium", "Domain"],
      ["true_false", "f(g(x)) generally equals g(f(x)).", null, "False", "hard", "Composite functions"],
      ["short_answer", "Inverse of f(x) = 2x?", null, "x/2", "medium", "Inverse functions"],
    ]),
  S("europe", "DP2", "Mathematics", "Calculus: Differentiation and Integration",
    "Differentiate and integrate polynomials; interpret results.",
    [
      ["calculation", "Differentiate y = x³ − 2x.", null, "3x² − 2", "Power rule term by term."],
      ["calculation", "Integrate ∫ (2x + 1) dx.", null, "x² + x + c", "Reverse the power rule; add + c."],
      ["short", "What does a stationary point require?", null, "dy/dx = 0", "Gradient is zero."],
      ["calculation", "Evaluate ∫ from 1 to 3 of 2x dx.", null, "8", "[x²] from 1 to 3 = 9 − 1 = 8."],
    ],
    "Connect derivatives (gradient) and integrals (area). Common error: omitting + c.",
    "Exit ticket", "Differentiate/integrate.",
    [
      ["short_answer", "d/dx of x⁴?", null, "4x³", "easy", "Differentiation"],
      ["short_answer", "∫ 3x² dx?", null, "x³ + c", "medium", "Integration"],
      ["true_false", "At a maximum point the gradient is 0.", null, "True", "medium", "Stationary points"],
      ["short_answer", "∫ from 0 to 2 of 3 dx?", null, "6", "medium", "Definite integrals"],
    ]),
];

// ── Africa (Pre-Primary 1 – Senior Secondary 3) ──────────────────────────────
const AF: Spec[] = [
  S("africa", "PP1", "Mathematics", "Counting Objects to 10",
    "Count the objects and say the number.",
    [
      ["short", "How many mangoes? 🥭🥭🥭🥭", null, "4", "Count each mango once."],
      ["short", "What comes after 6?", null, "7", "Count on from 6."],
      ["multiple_choice", "Which group has more?", ["5 goats", "2 goats"], "5 goats", "5 is more than 2."],
      ["short", "Count and write: ●●●", null, "3", "Three dots."],
    ],
    "Use local objects (stones, seeds) as counters.",
    "Quick check", "Say your answer.",
    [
      ["multiple_choice", "Which is more?", ["8", "3"], "8", "easy", "Comparing"],
      ["short_answer", "What comes before 5?", null, "4", "easy", "Number order"],
      ["true_false", "Nine is more than seven.", null, "True", "easy", "Number sense"],
      ["short_answer", "Count: ●●●●●", null, "5", "easy", "Counting"],
    ]),
  S("africa", "PP2", "English", "Letter Sounds and Simple Words",
    "Say the sound. Complete the word.",
    [
      ["short", "s _ n (it gives light in the sky)", null, "u", "The word is 'sun'."],
      ["short", "c _ p (you drink from it)", null, "u", "The word is 'cup'."],
      ["multiple_choice", "Which word starts with 'b'?", ["ball", "cat"], "ball", "'ball' begins with /b/."],
      ["short", "Write the first letter of 'dog'.", null, "d", "The /d/ sound."],
    ],
    "Model clear letter sounds. Use pictures for support.",
    "Quick check", "Choose the answer.",
    [
      ["multiple_choice", "Which starts with 'm'?", ["mat", "hat"], "mat", "easy", "Letter sounds"],
      ["short_answer", "First sound in 'pen'?", null, "p", "easy", "Phonics"],
      ["true_false", "'cat' starts with the /k/ sound.", null, "True", "easy", "Phonics"],
      ["multiple_choice", "Complete: 'b _ g'", ["a", "e"], "a", "easy", "Word building"],
    ]),
  S("africa", "P1", "Mathematics", "Addition and Subtraction to 20",
    "Add and subtract within 20.",
    [
      ["calculation", "8 + 7 = ?", null, "15", "8 + 2 = 10; 10 + 5 = 15."],
      ["calculation", "16 − 9 = ?", null, "7", "16 − 6 = 10; 10 − 3 = 7."],
      ["short", "Ama has 12 oranges and eats 5. How many are left?", null, "7", "12 − 5 = 7."],
      ["calculation", "9 + 9 = ?", null, "18", "Double 9 = 18."],
    ],
    "Use bundling of tens and ones. Encourage number bonds to 10.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "7 + 6 = ?", null, "13", "easy", "Addition"],
      ["short_answer", "20 − 8 = ?", null, "12", "easy", "Subtraction"],
      ["true_false", "9 + 4 = 13.", null, "True", "easy", "Addition"],
      ["multiple_choice", "Which makes 10?", ["6 + 4", "6 + 5"], "6 + 4", "medium", "Number bonds"],
    ]),
  S("africa", "P2", "Mathematics", "Place Value and Two-Digit Numbers",
    "Show tens and ones. Add two-digit numbers.",
    [
      ["short", "How many tens and ones in 47?", null, "4 tens and 7 ones", "47 = 40 + 7."],
      ["calculation", "35 + 24 = ?", null, "59", "30 + 20 = 50; 5 + 4 = 9; 59."],
      ["calculation", "68 − 30 = ?", null, "38", "Subtract 3 tens: 68 − 30 = 38."],
      ["short", "Write the number with 5 tens and 2 ones.", null, "52", "50 + 2 = 52."],
    ],
    "Use place-value charts. Common error: reversing tens and ones.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "Tens in 83?", null, "8", "easy", "Place value"],
      ["short_answer", "41 + 27 = ?", null, "68", "medium", "Addition"],
      ["true_false", "In 56, the 5 stands for 50.", null, "True", "easy", "Place value"],
      ["multiple_choice", "Which is 3 tens 4 ones?", ["34", "43"], "34", "easy", "Place value"],
    ]),
  S("africa", "P3", "Mathematics", "Multiplication Tables",
    "Recall multiplication facts and solve word problems.",
    [
      ["calculation", "5 × 6 = ?", null, "30", "Five sixes: 30."],
      ["calculation", "4 × 8 = ?", null, "32", "Four eights: 32."],
      ["short", "A basket has 6 eggs. How many eggs in 4 baskets?", null, "24", "6 × 4 = 24."],
      ["calculation", "27 ÷ 3 = ?", null, "9", "3 × 9 = 27."],
    ],
    "Use skip counting and arrays to build fluency.",
    "Exit ticket", "Answer each.",
    [
      ["short_answer", "7 × 4 = ?", null, "28", "easy", "Times tables"],
      ["short_answer", "36 ÷ 6 = ?", null, "6", "medium", "Division"],
      ["true_false", "3 × 8 = 24.", null, "True", "easy", "Times tables"],
      ["multiple_choice", "Which equals 40?", ["8 × 5", "8 × 6"], "8 × 5", "easy", "Times tables"],
    ]),
  S("africa", "P4", "Mathematics", "Fractions of Shapes and Numbers",
    "Find fractions of shapes and quantities.",
    [
      ["short", "What is 1/2 of 10?", null, "5", "10 ÷ 2 = 5."],
      ["short", "What is 1/4 of 12?", null, "3", "12 ÷ 4 = 3."],
      ["multiple_choice", "Which is larger?", ["1/2", "1/4"], "1/2", "One half is bigger than one quarter."],
      ["short", "A farmer harvests 20 bags and sells 1/5. How many sold?", null, "4", "20 ÷ 5 = 4."],
    ],
    "Use shaded shapes and sharing contexts (e.g., dividing fruit).",
    "Quick check", "Solve each.",
    [
      ["short_answer", "1/3 of 9 = ?", null, "3", "easy", "Fractions of amounts"],
      ["short_answer", "1/2 of 16 = ?", null, "8", "easy", "Fractions of amounts"],
      ["true_false", "1/4 is smaller than 1/2.", null, "True", "medium", "Comparing fractions"],
      ["multiple_choice", "How many quarters make a whole?", ["4", "2"], "4", "easy", "Fractions"],
    ]),
  S("africa", "P5", "Mathematics", "Decimals and Money",
    "Work with decimals and simple money problems.",
    [
      ["calculation", "2.5 + 1.3 = ?", null, "3.8", "Add tenths: 5 + 3 = 8; wholes 2 + 1 = 3."],
      ["short", "Write 3/10 as a decimal.", null, "0.3", "Three tenths."],
      ["calculation", "A pen costs 45 and a book 120. Total?", null, "165", "45 + 120 = 165."],
      ["calculation", "Change from 200 after spending 155?", null, "45", "200 − 155 = 45."],
    ],
    "Use local currency contexts. Line up decimal points when adding.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "0.6 + 0.2 = ?", null, "0.8", "easy", "Decimals"],
      ["short_answer", "1/2 as a decimal?", null, "0.5", "easy", "Conversions"],
      ["true_false", "0.7 is greater than 0.5.", null, "True", "medium", "Comparing decimals"],
      ["short_answer", "Change from 500 after spending 380?", null, "120", "medium", "Money"],
    ]),
  S("africa", "P6", "Mathematics", "Ratio, Percentage and Averages",
    "Solve ratio, percentage and average problems.",
    [
      ["calculation", "Find 25% of 160.", null, "40", "160 ÷ 4 = 40."],
      ["short", "Simplify the ratio 12:18.", null, "2:3", "Divide by 6."],
      ["calculation", "Find the mean of 4, 6 and 8.", null, "6", "(4 + 6 + 8) ÷ 3 = 6."],
      ["short", "Share 30 mangoes in the ratio 2:3. How many in the larger share?", null, "18", "5 parts → 6 each; 3 × 6 = 18."],
    ],
    "Link percentages, fractions and decimals. Reinforce the meaning of mean.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "10% of 250 = ?", null, "25", "easy", "Percentages"],
      ["multiple_choice", "8:12 simplifies to…", ["2:3", "3:2"], "2:3", "medium", "Ratio"],
      ["short_answer", "Mean of 5 and 9?", null, "7", "easy", "Averages"],
      ["true_false", "50% of 60 is 30.", null, "True", "easy", "Percentages"],
    ]),
  S("africa", "JSS1", "Mathematics", "Integers and Basic Algebra",
    "Work with integers and simple algebraic expressions.",
    [
      ["calculation", "−6 + 10 = ?", null, "4", "Count up from −6."],
      ["short", "Simplify: 3a + 5a", null, "8a", "Add like terms."],
      ["calculation", "Solve: x + 7 = 12", null, "x = 5", "Subtract 7 from both sides."],
      ["short", "If a = 4, find 2a + 3.", null, "11", "2(4) + 3 = 11."],
    ],
    "Introduce collecting like terms and substitution.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "−3 − 4 = ?", null, "−7", "easy", "Integers"],
      ["short_answer", "Simplify 6y − 2y.", null, "4y", "easy", "Like terms"],
      ["short_answer", "Solve x − 5 = 9.", null, "14", "medium", "Equations"],
      ["true_false", "3a + 2a = 5a.", null, "True", "easy", "Algebra"],
    ]),
  S("africa", "JSS2", "Integrated Science", "Photosynthesis",
    "Explain how green plants make food.",
    [
      ["short", "What gas do plants take in for photosynthesis?", null, "Carbon dioxide", "Absorbed from the air."],
      ["short", "What gas do plants release?", null, "Oxygen", "A product of photosynthesis."],
      ["long", "Write a word equation for photosynthesis.", null, "Carbon dioxide + water → (light + chlorophyll) → glucose + oxygen", "Rubric: correct reactants and products."],
      ["short", "What green substance traps light energy?", null, "Chlorophyll", "Found in chloroplasts."],
    ],
    "Emphasise the role of light and chlorophyll. Common misconception: plants get all their food from the soil.",
    "Quick check", "Choose or answer.",
    [
      ["multiple_choice", "Photosynthesis needs light and…", ["chlorophyll", "oxygen"], "chlorophyll", "medium", "Photosynthesis"],
      ["true_false", "Plants release oxygen during photosynthesis.", null, "True", "easy", "Photosynthesis"],
      ["short_answer", "Where in the leaf does photosynthesis mainly occur?", null, "Chloroplasts", "medium", "Plant biology"],
      ["multiple_choice", "The food made is…", ["glucose", "protein"], "glucose", "easy", "Photosynthesis"],
    ]),
  S("africa", "JSS3", "Mathematics", "Linear Equations and Word Problems",
    "Form and solve linear equations from word problems.",
    [
      ["calculation", "Solve: 2x + 5 = 17", null, "x = 6", "2x = 12; x = 6."],
      ["calculation", "Solve: 3(x − 2) = 12", null, "x = 6", "3x − 6 = 12; 3x = 18; x = 6."],
      ["short", "A number doubled and increased by 3 gives 15. Find the number.", null, "6", "2n + 3 = 15; n = 6."],
      ["calculation", "Solve: 5x − 4 = 2x + 11", null, "x = 5", "3x = 15; x = 5."],
    ],
    "Model translating words into equations. Balance both sides.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "4x = 28. x = ?", null, "7", "easy", "Equations"],
      ["short_answer", "x/3 = 4. x = ?", null, "12", "medium", "Equations"],
      ["true_false", "Doing the same to both sides keeps an equation balanced.", null, "True", "easy", "Equations"],
      ["short_answer", "2x − 1 = 9. x = ?", null, "5", "medium", "Equations"],
    ]),
  S("africa", "SSS1", "Mathematics", "Quadratic Equations",
    "Solve quadratic equations by factorisation.",
    [
      ["calculation", "Factorise: x² + 7x + 10", null, "(x + 2)(x + 5)", "2 × 5 = 10, 2 + 5 = 7."],
      ["calculation", "Solve: x² − 3x − 10 = 0", null, "x = 5 or x = −2", "(x − 5)(x + 2) = 0."],
      ["calculation", "Solve: x² − 25 = 0", null, "x = 5 or x = −5", "Difference of squares."],
      ["short", "State the roots of (x − 6)(x + 1) = 0.", null, "x = 6 and x = −1", "Zero-product property."],
    ],
    "Reinforce the zero-product property and sign patterns.",
    "Quick check", "Solve/factorise.",
    [
      ["short_answer", "Factorise x² + 4x + 3.", null, "(x + 1)(x + 3)", "medium", "Factorising"],
      ["short_answer", "Solve x² = 81.", null, "x = 9 or x = −9", "easy", "Quadratics"],
      ["true_false", "A quadratic equation can have two roots.", null, "True", "easy", "Quadratics"],
      ["multiple_choice", "Factorise x² − 4.", ["(x−2)(x+2)", "(x−4)(x+1)"], "(x−2)(x+2)", "medium", "Difference of squares"],
    ]),
  S("africa", "SSS2", "Mathematics", "Trigonometry",
    "Apply trigonometric ratios to right-angled triangles.",
    [
      ["short", "Write the ratio for tan θ.", null, "opposite / adjacent", "TOA."],
      ["calculation", "opposite = 5, hypotenuse = 13. Find sin θ.", null, "5/13 ≈ 0.385", "sin θ = opp/hyp."],
      ["short", "If cos θ = 0.5, find θ.", null, "60°", "cos⁻¹(0.5) = 60°."],
      ["calculation", "adjacent = 8, opposite = 6. Find tan θ.", null, "0.75", "6/8 = 0.75."],
    ],
    "Emphasise labelling sides relative to the angle.",
    "Exit ticket", "Solve each.",
    [
      ["multiple_choice", "sin θ = ?", ["opp/hyp", "adj/hyp"], "opp/hyp", "easy", "Trig ratios"],
      ["short_answer", "tan 45° = ?", null, "1", "medium", "Trig values"],
      ["true_false", "In any right triangle the hypotenuse is opposite the right angle.", null, "True", "easy", "Right triangles"],
      ["short_answer", "cos 0° = ?", null, "1", "hard", "Trig values"],
    ]),
  S("africa", "SSS3", "Mathematics", "Statistics: Mean, Median and Mode",
    "Calculate measures of central tendency.",
    [
      ["calculation", "Find the mean of 3, 7, 5, 9, 6.", null, "6", "Sum 30 ÷ 5 = 6."],
      ["short", "Find the median of 4, 8, 6, 2, 10.", null, "6", "Ordered: 2,4,6,8,10 → middle is 6."],
      ["short", "Find the mode of 2, 3, 3, 5, 7.", null, "3", "3 appears most often."],
      ["calculation", "Find the range of 12, 4, 9, 15.", null, "11", "15 − 4 = 11."],
    ],
    "Distinguish mean, median, mode and range. Order data before finding the median.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "Mean of 10 and 20?", null, "15", "easy", "Averages"],
      ["short_answer", "Median of 1, 2, 3, 4, 5?", null, "3", "easy", "Averages"],
      ["multiple_choice", "The most frequent value is the…", ["mode", "mean"], "mode", "medium", "Statistics"],
      ["short_answer", "Range of 5, 9, 2?", null, "7", "medium", "Statistics"],
    ]),
];

// ── Asia (Primary 1 – Junior College 2) ──────────────────────────────────────
const AS: Spec[] = [
  S("asia", "P1", "Mathematics", "Numbers and Addition to 20",
    "Count, compare and add numbers to 20.",
    [
      ["short", "What number comes after 14?", null, "15", "Count on from 14."],
      ["calculation", "9 + 6 = ?", null, "15", "9 + 1 = 10; 10 + 5 = 15."],
      ["multiple_choice", "Which is greater?", ["13", "11"], "13", "13 is more than 11."],
      ["calculation", "18 − 7 = ?", null, "11", "18 − 7 = 11."],
    ],
    "Use ten-frames to build number bonds to 10.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "7 + 8 = ?", null, "15", "easy", "Addition"],
      ["short_answer", "20 − 6 = ?", null, "14", "easy", "Subtraction"],
      ["true_false", "16 is greater than 12.", null, "True", "easy", "Comparing"],
      ["multiple_choice", "Which makes 10?", ["3 + 7", "3 + 8"], "3 + 7", "medium", "Number bonds"],
    ]),
  S("asia", "P2", "English", "Nouns and Simple Sentences",
    "Identify nouns and write simple sentences.",
    [
      ["multiple_choice", "Which word is a noun?", ["table", "quickly"], "table", "A noun names a person, place or thing."],
      ["short", "Write the plural of 'box'.", null, "boxes", "Add -es after x."],
      ["long", "Write a sentence about your school.", null, "Answers vary, e.g. 'My school has a big garden.'", "Rubric: capital letter, a noun used, full stop."],
      ["short", "Underline the noun: 'The bird sang.'", null, "bird", "'bird' is the naming word."],
    ],
    "Reinforce that nouns are naming words. Practise regular plurals.",
    "Quick check", "Choose the answer.",
    [
      ["multiple_choice", "Which is a noun?", ["river", "run"], "river", "easy", "Nouns"],
      ["short_answer", "Plural of 'baby'?", null, "babies", "medium", "Plurals"],
      ["true_false", "A sentence starts with a capital letter.", null, "True", "easy", "Punctuation"],
      ["multiple_choice", "Pick the sentence.", ["Cats like milk.", "like milk"], "Cats like milk.", "easy", "Sentences"],
    ]),
  S("asia", "P3", "Mathematics", "Multiplication and Division",
    "Recall tables and solve division problems.",
    [
      ["calculation", "6 × 8 = ?", null, "48", "Six eights: 48."],
      ["calculation", "42 ÷ 7 = ?", null, "6", "7 × 6 = 42."],
      ["short", "A classroom has 4 rows of 6 desks. How many desks?", null, "24", "4 × 6 = 24."],
      ["calculation", "9 × 7 = ?", null, "63", "Nine sevens: 63."],
    ],
    "Build fluency with the times tables; relate division as the inverse.",
    "Exit ticket", "Answer each.",
    [
      ["short_answer", "8 × 6 = ?", null, "48", "easy", "Times tables"],
      ["short_answer", "56 ÷ 8 = ?", null, "7", "medium", "Division"],
      ["true_false", "7 × 9 = 63.", null, "True", "easy", "Times tables"],
      ["multiple_choice", "Which equals 36?", ["6 × 6", "6 × 7"], "6 × 6", "easy", "Times tables"],
    ]),
  S("asia", "P4", "Mathematics", "Fractions and Decimals",
    "Compare fractions and convert to decimals.",
    [
      ["short", "Write 1/4 as a decimal.", null, "0.25", "1 ÷ 4 = 0.25."],
      ["multiple_choice", "Which is larger?", ["2/3", "1/3"], "2/3", "Two thirds is bigger."],
      ["short", "What is 3/5 of 20?", null, "12", "20 ÷ 5 = 4; 4 × 3 = 12."],
      ["calculation", "0.4 + 0.3 = ?", null, "0.7", "Add the tenths."],
    ],
    "Use fraction bars and place-value charts to link fractions and decimals.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "1/2 as a decimal?", null, "0.5", "easy", "Conversions"],
      ["short_answer", "1/4 of 16 = ?", null, "4", "medium", "Fractions of amounts"],
      ["true_false", "0.75 = 3/4.", null, "True", "medium", "Conversions"],
      ["multiple_choice", "Which is bigger?", ["0.6", "0.45"], "0.6", "easy", "Decimals"],
    ]),
  S("asia", "P5", "Mathematics", "Percentage and Ratio",
    "Solve percentage and ratio problems.",
    [
      ["calculation", "Find 20% of 150.", null, "30", "150 ÷ 5 = 30."],
      ["short", "Simplify the ratio 9:12.", null, "3:4", "Divide by 3."],
      ["calculation", "A shirt costs $80 with 15% discount. Discount amount?", null, "$12", "15% of 80 = 12."],
      ["short", "Share 24 sweets in the ratio 1:3. Larger share?", null, "18", "4 parts → 6 each; 3 × 6 = 18."],
    ],
    "Connect percentages, fractions and ratios.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "10% of 90 = ?", null, "9", "easy", "Percentages"],
      ["multiple_choice", "6:8 simplifies to…", ["3:4", "4:3"], "3:4", "medium", "Ratio"],
      ["short_answer", "25% of 40 = ?", null, "10", "easy", "Percentages"],
      ["true_false", "A discount reduces the price.", null, "True", "easy", "Percentages"],
    ]),
  S("asia", "P6", "Mathematics", "Speed, Distance and Time",
    "Use the relationship speed = distance ÷ time.",
    [
      ["calculation", "A car travels 120 km in 2 hours. Find its speed.", null, "60 km/h", "120 ÷ 2 = 60."],
      ["calculation", "At 50 km/h for 3 hours, distance travelled?", null, "150 km", "50 × 3 = 150."],
      ["short", "A train covers 180 km at 60 km/h. Time taken?", null, "3 hours", "180 ÷ 60 = 3."],
      ["calculation", "Speed of 90 km in 1.5 hours?", null, "60 km/h", "90 ÷ 1.5 = 60."],
    ],
    "Use the speed–distance–time triangle. Watch unit consistency.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "Distance = speed × ?", null, "time", "easy", "Speed formula"],
      ["short_answer", "100 km in 2 h = ? km/h", null, "50", "easy", "Speed"],
      ["true_false", "Time = distance ÷ speed.", null, "True", "medium", "Speed formula"],
      ["short_answer", "60 km/h for 4 h covers ? km", null, "240", "medium", "Distance"],
    ]),
  S("asia", "S1", "Mathematics", "Integers and Algebraic Expressions",
    "Work with integers and simplify expressions.",
    [
      ["calculation", "−8 + 15 = ?", null, "7", "Count up from −8."],
      ["short", "Simplify: 4x + 3x − 2x", null, "5x", "Collect like terms."],
      ["short", "If x = 3, find 2x² .", null, "18", "2 × 9 = 18."],
      ["calculation", "Solve: x + 9 = 4", null, "x = −5", "Subtract 9 from both sides."],
    ],
    "Introduce collecting like terms and substitution with negatives.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "−5 + 12 = ?", null, "7", "easy", "Integers"],
      ["short_answer", "Simplify 7a − 3a.", null, "4a", "easy", "Like terms"],
      ["true_false", "(−3)² = 9.", null, "True", "medium", "Integers"],
      ["short_answer", "Solve x − 4 = −1.", null, "3", "medium", "Equations"],
    ]),
  S("asia", "S2", "Mathematics", "Linear Equations and Graphs",
    "Solve equations and interpret y = mx + c.",
    [
      ["calculation", "Solve: 3x − 7 = 8", null, "x = 5", "3x = 15; x = 5."],
      ["short", "In y = 4x − 2, state the gradient.", null, "4", "Coefficient of x."],
      ["calculation", "Solve: 2(x + 3) = 16", null, "x = 5", "2x + 6 = 16; 2x = 10; x = 5."],
      ["short", "Where does y = x + 3 cross the y-axis?", null, "(0, 3)", "c = 3."],
    ],
    "Connect algebra and graphs; identify gradient and intercept.",
    "Quick check", "Solve/interpret.",
    [
      ["short_answer", "5x + 5 = 30. x = ?", null, "5", "easy", "Equations"],
      ["multiple_choice", "Gradient of y = −2x + 1?", ["−2", "1"], "−2", "medium", "Graphs"],
      ["true_false", "Parallel lines have equal gradients.", null, "True", "medium", "Graphs"],
      ["short_answer", "Solve 4x − 9 = 3.", null, "3", "medium", "Equations"],
    ]),
  S("asia", "S3", "Mathematics", "Quadratic Equations",
    "Solve quadratics by factorisation.",
    [
      ["calculation", "Factorise: x² + 9x + 20", null, "(x + 4)(x + 5)", "4 × 5 = 20, 4 + 5 = 9."],
      ["calculation", "Solve: x² − 7x + 12 = 0", null, "x = 3 or x = 4", "(x − 3)(x − 4) = 0."],
      ["calculation", "Solve: x² − 49 = 0", null, "x = 7 or x = −7", "Difference of squares."],
      ["short", "Roots of (x + 2)(x − 9) = 0?", null, "x = −2 and x = 9", "Zero-product property."],
    ],
    "Reinforce the zero-product property; watch signs of the constant term.",
    "Exit ticket", "Solve/factorise.",
    [
      ["short_answer", "Factorise x² + 2x + 1.", null, "(x + 1)²", "medium", "Perfect squares"],
      ["short_answer", "Solve x² = 64.", null, "x = 8 or x = −8", "easy", "Quadratics"],
      ["true_false", "x² − 1 = (x − 1)(x + 1).", null, "True", "medium", "Difference of squares"],
      ["multiple_choice", "A quadratic graph is a…", ["parabola", "straight line"], "parabola", "easy", "Graphs"],
    ]),
  S("asia", "S4", "Mathematics", "Trigonometry and Pythagoras",
    "Apply Pythagoras' theorem and basic trigonometry.",
    [
      ["calculation", "A right triangle has legs 3 and 4. Find the hypotenuse.", null, "5", "√(3² + 4²) = √25 = 5."],
      ["short", "State Pythagoras' theorem.", null, "a² + b² = c² (c is the hypotenuse)", "Right-triangle relationship."],
      ["calculation", "opposite = 6, hypotenuse = 10. Find sin θ.", null, "0.6", "6/10 = 0.6."],
      ["short", "If tan θ = 1, find θ.", null, "45°", "tan 45° = 1."],
    ],
    "Combine Pythagoras with trig ratios. Identify the hypotenuse correctly.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "Legs 6 and 8: hypotenuse?", null, "10", "medium", "Pythagoras"],
      ["multiple_choice", "cos θ = ?", ["adj/hyp", "opp/hyp"], "adj/hyp", "easy", "Trig ratios"],
      ["true_false", "The hypotenuse is the longest side.", null, "True", "easy", "Right triangles"],
      ["short_answer", "sin 30° = ?", null, "0.5", "hard", "Trig values"],
    ]),
  S("asia", "S5", "Mathematics", "Probability",
    "Calculate probabilities of simple events.",
    [
      ["short", "A fair die is rolled. Probability of a 4?", null, "1/6", "One favourable out of six."],
      ["short", "Probability of an even number on a die?", null, "1/2 (3/6)", "2, 4, 6 are even."],
      ["short", "A bag has 3 red and 2 blue balls. P(red)?", null, "3/5", "3 red out of 5."],
      ["calculation", "P(not red) in the bag above?", null, "2/5", "1 − 3/5 = 2/5."],
    ],
    "Emphasise favourable ÷ total outcomes and the complement rule.",
    "Exit ticket", "Solve each.",
    [
      ["short_answer", "P(head) on a fair coin?", null, "1/2", "easy", "Probability"],
      ["multiple_choice", "P(getting 7 on a die)?", ["0", "1/6"], "0", "medium", "Impossible events"],
      ["true_false", "Probabilities are between 0 and 1.", null, "True", "easy", "Probability"],
      ["short_answer", "P(certain event)?", null, "1", "easy", "Probability"],
    ]),
  S("asia", "JC1", "Mathematics", "Functions and Differentiation",
    "Work with functions and differentiate polynomials.",
    [
      ["calculation", "If f(x) = x² + 1, find f(3).", null, "10", "9 + 1 = 10."],
      ["calculation", "Differentiate y = x³ + 2x.", null, "3x² + 2", "Power rule term by term."],
      ["short", "What does dy/dx represent?", null, "The gradient / rate of change.", "Slope of the tangent."],
      ["calculation", "Gradient of y = x² at x = 4?", null, "8", "dy/dx = 2x; 2(4) = 8."],
    ],
    "Reinforce the power rule and function notation.",
    "Quick check", "Solve each.",
    [
      ["short_answer", "d/dx of x⁵?", null, "5x⁴", "medium", "Differentiation"],
      ["short_answer", "f(x)=2x+1, f(5)?", null, "11", "easy", "Functions"],
      ["true_false", "The derivative of a constant is 0.", null, "True", "medium", "Differentiation"],
      ["short_answer", "Gradient of y = 3x² at x = 1?", null, "6", "hard", "Differentiation"],
    ]),
  S("asia", "JC2", "Mathematics", "Integration",
    "Integrate polynomials and evaluate definite integrals.",
    [
      ["calculation", "∫ (3x² + 2) dx = ?", null, "x³ + 2x + c", "Reverse the power rule; add + c."],
      ["calculation", "∫ from 0 to 2 of 3x² dx = ?", null, "8", "[x³] from 0 to 2 = 8."],
      ["short", "Why include '+ c' for an indefinite integral?", null, "The constant is lost when differentiating, so it is unknown.", "Family of antiderivatives."],
      ["calculation", "∫ 4x dx = ?", null, "2x² + c", "Raise power, divide by new power."],
    ],
    "Connect integration as the reverse of differentiation; interpret definite integrals as area.",
    "Exit ticket", "Integrate/evaluate.",
    [
      ["short_answer", "∫ x² dx = ?", null, "x³/3 + c", "medium", "Integration"],
      ["short_answer", "∫ from 1 to 2 of 2x dx = ?", null, "3", "hard", "Definite integrals"],
      ["true_false", "A definite integral can represent area under a curve.", null, "True", "medium", "Definite integrals"],
      ["short_answer", "∫ 6 dx = ?", null, "6x + c", "easy", "Integration"],
    ]),
];

const ALL_SPECS: Spec[] = [...US, ...UK, ...EU, ...AF, ...AS];

function gradeLabel(region: string, yg: string): string {
  const r = getRegion(region);
  const found = r?.yearGroups.find((g) => g.value === yg);
  return found?.label ?? yg;
}

type SampleRow = typeof samplesTable.$inferInsert;

export function buildSampleRows(): SampleRow[] {
  const rows: SampleRow[] = [];
  for (const g of ALL_SPECS) {
    const label = gradeLabel(g.region, g.yg);
    // Worksheet
    rows.push({
      kind: "worksheet",
      region: g.region,
      subject: g.subject,
      yearGroup: g.yg,
      title: `${g.topic} — Practice Worksheet`,
      description: `A ready-to-use ${g.subject} worksheet on ${g.topic.toLowerCase()} for ${label}. Copy it to your library to adapt and assign.`,
      content: {
        title: `${g.topic} — Practice Worksheet`,
        instructions: g.wsInstr,
        questions: g.ws.map((q, i) => ({
          number: i + 1,
          prompt: q[1],
          type: q[0],
          options: q[2],
          answer: q[3],
          workingOrRubric: q[4],
        })),
        teacherNotes: g.wsNotes,
      },
    });
    // Quiz
    rows.push({
      kind: "quiz",
      region: g.region,
      subject: g.subject,
      yearGroup: g.yg,
      title: `${g.topic} — Quick Check`,
      description: `A short ${g.subject} quiz on ${g.topic.toLowerCase()} for ${label}. Copy it to your library to adapt and assign.`,
      content: {
        title: `${g.topic} — Quick Check`,
        format: g.qzFormat,
        instructions: g.qzInstr,
        items: g.qz.map((q, i) => ({
          number: i + 1,
          prompt: q[1],
          type: q[0],
          options: q[2],
          correctAnswer: q[3],
          difficulty: q[4],
          skillAssessed: q[5],
        })),
      },
    });
  }
  return rows;
}

/** Insert the full sample set only if the samples table is currently empty. */
export async function seedSamplesIfEmpty(): Promise<{ seeded: boolean; count: number }> {
  const [row] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(samplesTable);
  const existing = row?.count ?? 0;
  if (existing > 0) return { seeded: false, count: existing };
  const rows = buildSampleRows();
  await db.insert(samplesTable).values(rows);
  return { seeded: true, count: rows.length };
}

/** Force a full refresh: delete every sample and re-insert the seed set. */
export async function reseedSamples(): Promise<{ count: number }> {
  const rows = buildSampleRows();
  await db.delete(samplesTable);
  await db.insert(samplesTable).values(rows);
  return { count: rows.length };
}
